### ISSUE TITLE
Contao 3.5.24 und Contao 4.3.2: Probleme mit Inhaltselementen

### ISSUE THREAD

**Issue by minstyle** [terminal42/contao-changelanguage#101]
Die Erweiterung **changelanguage Version 3.1.0 Build 4** verursacht Probleme im Backend von Contao:

So können Inhaltselemente in der Artikelansicht von Seiten nicht mehr über das Augen-Icon auf sichtbar/unsichtbar geschaltet werden.

Hier habe ich das Problem ausführlich beschrieben:

https://github.com/contao/core/issues/8634

**Comment by aschempp** [comment]
This is probably a bug in `ce-access` (according to the stack trace)

**Comment by minstyle** [comment]
Vielen Dank für die Antwort.

Wenn ich die Erweiterung `changelanguage` deaktiviere, dann tritt der Fehler mit den Inhaltselementen nicht mehr auf. Wie kann das Problem denn nun gelöst werden?

**Comment by fritzmg** [comment]
> This is probably a bug in ce-access (according to the stack trace)

The `$GLOBALS['TL_DCA']['tl_content']['config']['onload_callback']` callback passes either a `tl_content` object or a `DataContainer` object. However, your callback expects it to be a `DataContainer` object and thus it fails.

The `tl_content::toggleVisibility` function has an optional third parameter where you can pass a `DataContainer` object. It is `null` by default. If no `DataContainer` object is passed, the function will instead pass `$this` [here](https://github.com/contao/core/blob/3.5.24/system/modules/core/dca/tl_content.php#L1765) - which will be an object of type `tl_content` instead.

**Comment by minstyle** [comment]
@fritzmg 

Ich habe deine Änderungen in der entsprechenden Datei vollzogen und den Cache von Contao gelöscht. Das Problem besteht leider immer noch. Oder habe ich etwas falsch gemacht?

**Comment by fritzmg** [comment]
Wie lautet die genaue Fehlermeldung? Hast du auch tatsächlich _alle_  Änderungen gemacht, inkl. der Signaturänderung der Funktion?

**Comment by minstyle** [comment]
In den DevTools von Google Chrome werden mir keine Fehlermeldungen angezeigt. Ich habe nur den Cache geleert. Wie kann man denn die "Signaturänderung der Funktion" durchführen?

**Comment by fritzmg** [comment]
Wie bist du zuvor zur Fehlermeldung gekommen?

**Comment by minstyle** [comment]
Auch über DevTools.

**Comment by fritzmg** [comment]
Steht etwas im error.log wenn du die Ausgabe der Fehlermeldungen im Frontend deaktivierst?

**Comment by minstyle** [comment]
Folgende Fehlermeldung erscheint in der `/system/logs/error.log`:

```
[03-Feb-2017 16:36:00 Europe/Berlin] PHP Fatal error: Uncaught exception 'TypeError' with message 'Argument 1 passed to Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener::Terminal42\ChangeLanguage\EventListener\BackendView\{closure}() must be an instance of Contao\DataContainer, instance of tl_content given, called in /usr/www/users/exap5810/system/modules/core/dca/tl_content.php on line 1765' thrown in /usr/www/users/exap5810/system/modules/changelanguage/library/Terminal42/ChangeLanguage/EventListener/BackendView/AbstractViewListener.php on line 52
#0 /usr/www/users/exap5810/system/modules/core/dca/tl_content.php(1765): Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener->Terminal42\ChangeLanguage\EventListener\BackendView\{closure}(Object(tl_content))
#1 /usr/www/users/exap5810/system/modules/core/dca/tl_content.php(1705): tl_content->toggleVisibility('28', false, NULL)
#2 /usr/www/users/exap5810/system/modules/ce-access/CeAccess.php(148): tl_content->toggleIcon(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...')
#3 /usr/www/users/exap5810/system/modules/core/classes/DataContainer.php(683): CeAccess->toggleButton(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...', 'tl_content', NULL, NULL, false, NULL, '29', Object(Contao\DC_Table))
#4 /usr/www/users/exap5810/system/modules/core/drivers/DC_Table.php(4241): Contao\DataContainer->generateButtons(Array, 'tl_content', NULL, false, NULL, NULL, '29')
#5 /usr/www/users/exap5810/system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#6 /usr/www/users/exap5810/system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#7 /usr/www/users/exap5810/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#8 /usr/www/users/exap5810/contao/main.php(20): Contao\BackendMain->run()
#9 {main}```

**Comment by fritzmg** [comment]
Wie sieht die Definition der `onLoad` Funktion in deiner `AbstractViewListener` Klasse nun aus?

**Comment by fritzmg** [comment]
Und wo hast du diese Änderung gemacht? Wenn du die Extension über Composer installiert hast, dann musst du die Änderung wahrscheinlich im `/composer/vendor/...` Ordner machen  nicht im `/system/modules/...` Ordner.

**Comment by minstyle** [comment]
Ich nutze Contao 3.5.24.

**Comment by fritzmg** [comment]
Das beantwortet keine meiner Fragen ;)

**Comment by minstyle** [comment]
Im der Datei `\system\modules\changelanguage\library\Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener.php` habe ich folgendes stehen (Zeilen 52-70):

```
        $GLOBALS['TL_DCA'][$this->table]['config']['onload_callback'][] = function (DataContainer $dc) {
            $this->onLoad($dc);
        };
    }

    /**
     * Handler for onload_callback.
     *
     * @param DataContainer $dc
     */
    public function onLoad($dc)
    {
        if (!$dc instanceof DataContainer) {
            return;
        }

        if ($dc->table !== $this->table) {
            return;
        }
```

**Comment by fritzmg** [comment]
Ah, eine Zeile habe ich im commit vergessen. Entferne die `DataContainer` Klasse in Zeile 52.

**Comment by minstyle** [comment]
Perfekt, dank deiner Hilfe funktioniert es jetzt endlich wieder! Du bist mein Held des Tages ;)

Zeile 52 sind nun jetzt bei mir so aus:

        `$GLOBALS['TL_DCA'][$this->table]['config']['onload_callback'][] = function ($dc) {`

Wäre schon, wenn der Bugfix bei dem nächsten changelanguage-Update allen Benutzern zur Verfügung steht.

**Comment by aschempp** [comment]
Can you check if the 2.0.4 version of ce-access (https://github.com/terminal42/contao-ce-access/tree/hotfix/2.0.4) fixes the issue?

**Comment by fritzmg** [comment]
This bug can happen with any extension, or even within Contao in theory, since it is actually Contao that deliberately passes the second parameter as something else than `\DataContainer`.
