### ISSUE TITLE
Missing root page for language "xx"

### ISSUE THREAD

**Issue by k-webdesign** [terminal42/contao-changelanguage#102]
Hi,

nach dem Update von der changelanguage 2 auf die 3.1.0 hab ich ein seltsames Verhalten bemerkt. Die betroffene Seite ist 3-sprachig und lief unter changelanguage 2 sauber. Die .ch-Domain ist problemlos aufrufbar, vermutlich weil sie der erste Startpunkt ist. Wechsle ich nun die Sprache auf egal welcher Seite, und möchte damit auf einen anderen Seitenbaum springen, kommt bei der .com-Domain das hier (und bei der .fr-Domain meckert es wegen der fehlenden "en"):

Fatal error: Uncaught exception RuntimeException with message Missing root page for language "fr" thrown in composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php on line 128
#0 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php(65): Terminal42\ChangeLanguage\Navigation\NavigationFactory->setTargetPageForNavigationItems(Array, Array, Array)
#1 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(71): Terminal42\ChangeLanguage\Navigation\NavigationFactory->findNavigationItems(Object(Contao\PageModel))
#2 system/modules/core/modules/Module.php(287): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->compile()
#3 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#4 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(51): Haste\Frontend\AbstractFrontendModule->generate()
#5 system/modules/core/library/Contao/Controller.php(321): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->generate()
#6 system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('6')
#7 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#8 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#9 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#10 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 index.php(20): Contao\FrontendIndex->run()
#12 {main}

Die Konfiguration im Seitenbaum sieht wie folgt aus:
![changelanguage](https://cloud.githubusercontent.com/assets/4130440/22514868/fcd88e8e-e8a0-11e6-980b-c2cf3344e39e.jpg). Die Seiten haben alle ihr Fallback zugewiesen bekommen, daher gehe ich davon aus, dass meine Konfiguration korrekt ist - unter v2 lief es ja :) 

Xtra meinte, es könnte ggf. etwas mit https://github.com/terminal42/contao-changelanguage/pull/99 zu tun haben. News4ward wird zwar nicht benutzt, aber Listen von News und MetaModels. 

Wenn ich noch irgendwo was liefern soll, bitte Bescheid geben.

**Comment by aschempp** [comment]
sind die Root-Seiten veröffentlicht? Mit #99 hat es nichts zu tun, das betrifft nur Backend.

**Comment by aschempp** [comment]
womöglich das gleiche wie #96?

**Comment by k-webdesign** [comment]
Die Root-Seiten sind alle veröffentlicht. Es ist dieselbe Installation wie die Live-Seite unter Changelanguage 2, mit derselben Konfiguration. Daher schließe ich #96 aus.

**Comment by k-webdesign** [comment]
Auch in der 3.1.1 noch reproduzierbar

**Comment by Stefanmelz** [comment]
Ich schließe mich dem an. Musste auf V. 2.2.10 zurück. Da geht es.

**Comment by Xendiadyon** [comment]
Ich weiß nicht, ob dieser Fehler identisch ist:

Wir haben 3 Sprachen definiert. Englisch als Hauptsprache/Fallback, dazu deutsch und polnisch.

Wenn wir nun die Frontend-Vorschau öffnen und dort unveröffentlichte Elemente anzeigen, bekommen wir immer die "kein Startpunkt definiert" Fehlermeldung. Egal, welche Seite wir aufrufen, egal in welcher Sprache.

![image](https://cloud.githubusercontent.com/assets/2657385/23358865/edfa66e2-fce3-11e6-936f-56aa2d181b05.png)
In der Serverkonsole bekommen wir eine Fehlermeldung für https://domain.de/de/ (oder domain.de/en oder domain.de/pl)

Wenn wir die unveröffentlichten Elemente wieder ausblenden, klappt es problemlos und die domain.de/de/ usw. werden korrekt angezeigt.

In den Einstellungen ist "Sprache an die URL anhängen" aktiviert.

Die deutschen und englischen Startpunkte sind auch korrekt definiert:
![image](https://cloud.githubusercontent.com/assets/2657385/23359002/837d49fa-fce4-11e6-981a-cb4b36f887d3.png)

![image](https://cloud.githubusercontent.com/assets/2657385/23359018/913bab68-fce4-11e6-8cae-dac6dc86d48d.png)


```
[27-Feb-2017 11:35:47 Europe/Berlin] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Missing root page for language "en"' thrown in /pfad-zum-contao/htdocs/system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php on line 135
#0 /pfad-zum-contao/htdocs/system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php(64): Terminal42\ChangeLanguage\Navigation\NavigationFactory->setTargetPageForNavigationItems(Array, Array, Array)
#1 /pfad-zum-contao/htdocs/system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(71): Terminal42\ChangeLanguage\Navigation\NavigationFactory->findNavigationItems(Object(Contao\PageModel))
#2 /pfad-zum-contao/htdocs/system/modules/core/modules/Module.php(287): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->compile()
#3 /pfad-zum-contao/htdocs/system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#4 /pfad-zum-contao/htdocs/system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(51): Haste\Frontend\AbstractFrontendModule->generate()
#5 /pfad-zum-contao/htdocs/system/modules/core/library/Contao/Controller.php(321): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->generate()
#6 /pfad-zum-contao/htdocs/system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('5')
#7 /pfad-zum-contao/htdocs/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<!DOCTYPE html>...', false)
#8 /pfad-zum-contao/htdocs/system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('<!DOCTYPE html>...', false)
#9 /pfad-zum-contao/htdocs/system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#10 /pfad-zum-contao/htdocs/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 /pfad-zum-contao/htdocs/index.php(20): Contao\FrontendIndex->run()
#12 {main}

```

**Comment by aschempp** [comment]
Fixed in 0c578753597077e454e16b09f0068324bd9b5d08

**Comment by Xendiadyon** [comment]
@aschempp Sorry, Andreas, dass ich noch mal nerve. Wir haben jetzt auf 3.1.2 aktualisiert, der Fehler https://github.com/terminal42/contao-changelanguage/issues/102#issuecomment-282691015 tritt aber noch immer auf.

Es wird keine PHP-Fehlermeldung generiert, aber der Hinweis "Keinen Startpunkt gefunden" kommt trotzdem noch bei der Frontendvorschau, sobald man die "versteckte Elemente anzeigen" aktiviert.

Könntest du bitte noch mal überprüfen, ob du das nachvollziehen kannst?

**Comment by aschempp** [comment]
@Xendiadyon das ist kein Fehler in ChangeLanguage. Die Frontend-Vorschau funktioniert nur auf der Domain auf welcher du im Backend eingeloggt bist. Entsprechend gibt es auf den weiteren Domains keine sichtbaren Seiten und daher kommt der Fehler.

**Comment by Xendiadyon** [comment]
@aschempp Du hast Recht. Ich habe ein einfaches, aktuelles Testsystem gebaut und der Fehler tritt nicht auf. Auch nicht mit htaccess-Geschribbsel und mehreren Sprachen.
Auf unserem anderen, fehlerhaften System tritt dieser Fehler weiterhin auf. Allerdings nicht mehr, sobald die Erweiterung changelanguage deaktiviert ist.

Also: irgendwas muss es schon damit zu tun haben, aber changelanguage ist nicht (alleine) Schuld, dass dieser Fehler bei uns auftritt. Ich schau mal, ob ich die Zeit finde, da noch tiefer nachzuforschen.

**Comment by aschempp** [comment]
Falls du was findest mach bitte ein neues Issue, das hier ist schon erledigt.

**Comment by Anke** [comment]
Ich habe wohl dasselbe Problem. Installiert sind Contao 3.5.24 sowie changelanguage 3.1.2 Build 3 und newslanguage 2.11.15.

Der erste Websistestartpunkt hat die Fallbacksprache Englisch und soll mit einer .com-Domain aufgerufen werden. Der zweite Websitestartpunkt soll auf eine .de-Domain hören. Das funktioniert bei deaktiviertem changelanguage und newslanguage.

Mit aktivem changelanguage erhalte ich beim Aufruf der .com-Domain, also der englischen Seite, folgende Meldung:

```
Fatal error: Uncaught exception RuntimeException with message Missing root page for language "en" thrown in system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php on line 134

#0 system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php(65): Terminal42\ChangeLanguage\Navigation\NavigationFactory->setTargetPageForNavigationItems(Array, Array, Array)
#1 system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(70): Terminal42\ChangeLanguage\Navigation\NavigationFactory->findNavigationItems(Object(Contao\PageModel))
#2 system/modules/core/modules/Module.php(287): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->compile()
#3 system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#4 system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(50): Haste\Frontend\AbstractFrontendModule->generate()
#5 system/modules/core/library/Contao/Controller.php(321): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->generate()
#6 system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('7')
#7 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#8 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#9 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#10 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 index.php(20): Contao\FrontendIndex->run()
#12 {main}

```
Außerdem steht im Backend in der Seitenstruktur in diesem Fall:

`Bei keinem der aktiven Website-Startpunkte für xxx.de wurde die Option "Sprachen-Fallback" ausgewählt, d.h. diese Webseiten sind nur in der einen Sprache verfügbar, die in den Seiteneinstellungen definiert wurde! Besucher und Suchmaschinen, die diese Sprache nicht sprechen, können die Webseite nicht aufrufen.
`

Das Sprachenfallback ist aber für die englische Website eingerichtet. 

Hier weiß ich nicht weiter ...

**Comment by fritzmg** [comment]
> changelanguage 3.1.2 Build 3 und newslanguage 2.11.15.

Wenn du changelanguage 3.x verwendest, darfst du nicht newslanguage auch verwenden. newslanguage ist nur für changelanguage 2.x.

**Comment by Anke** [comment]
Ah, danke für die Info. Ohne newslanguage ändert sich allerdings nichts am oben beschriebenen Verhalten.

**Comment by fritzmg** [comment]
Lösche changelanguage lieber nochmal komplett und installiere es neu.

**Comment by Anke** [comment]
Die DB-Einträge kann ich für die Neuinstallation aber bestehen lassen? Das sind ein Haufen Seiten ...

**Comment by fritzmg** [comment]
Ja, du brauchst nichts droppen.

**Comment by Anke** [comment]
Danke. Okay, habe changelanguage neu installiert. Fehlermeldungen zunächst wie gehabt, vor allem in der Seitenstruktur. Also habe ich testweise bei beiden Websitestartpunkten/Sprachversionen ein Häkchen bei Fallbacksprache gesetzt. Damit sind beide Websites (deutsch und englisch) ohne Fehlermeldungen aufrufbar, allerdings ist das Sprachenwechsler-Menü jetzt verschwunden.

Ist das richtig so - mit zwei Fallbacksprachen und dass unter diesen Bedingungen die Sprache nicht mehr per changelaguage gewechselt werden kann? Ich bin verwirrt.

**Comment by Anke** [comment]
@fritzmg - Herzlichen Dank für deine Hilfe. Die Fehlermeldungen bleiben jetzt weg, wenn ich beide Sprachbäume unter den jeweiligen Domains als Fallbacksprachen definiere und die Fremd-Domain-Hauptsprache richtig auswähle. (Hatte bisher nur Erfahrung mit mehreren Sprachen unter einer Domain.)
