### ISSUE TITLE
Update von 3.1.0 auf 3.1.1 - Nachrichten, Events werden nicht mehr unterstützt??

### ISSUE THREAD

**Issue by Samson1964** [terminal42/contao-changelanguage#103]
Habe gerade die aktuelle 3.1.1 build 2 aus dem ER gezogen. Seitdem sind im BE die Relationen zum Hauptnachrichtenarchiv und zum Haupteventarchiv verschwunden. Die Erweiterungsverwaltung bietet mir das Löschen der master-Spalte an. Auch im FE ist der Sprachwechsler verschwunden und ich kann nicht mehr zur Nachricht der anderen Sprache(n) wechseln.

Ist das ein Versehen? master in tl_news_archive hat ohnehin nicht richtig funktioniert. Ich mußte das master-Archiv direkt mit phpMyAdmin eintragen, da im BE keine Auswahl möglich war bzw. eine vorhandene Auswahl gelöscht wird.

Ich ziehe mir sicherheitshalber manuell die 3.1.0 wieder rauf.

**Comment by joergmoldenhauer** [comment]
There seems to be a problem with the adding of the column "master" in certain database tables. For example the column "master" is not added to "tl_news_archive" when I install the extension via the old extension manager in Contao 3.5.24. I am not sure if the problem also accurs when you install the extension via composer.

I had a quick look at the code and the problem might be in the file "library\Terminal42\ChangeLanguage\EventListener\DataContainer\ParentTableListener.php". In an older version of changelanguage the column was added in the "register" Method. Now it is added in the "onLoad" Method.
