### ISSUE TITLE
Hook changelanguageNavigation - Sprache abfragen

### ISSUE THREAD

**Issue by Total-Reality** [terminal42/contao-changelanguage#105]
Hi,

Bei eurer Version 2.x hab es ja die Möglichkeit die Sprache auszulesen und so die Items im Sprachwechsler-Modul entsprechend abzuändern.

Es hieß ja vorher "translateUrlParameters"

```
$GLOBALS['TL_HOOKS']['translateUrlParameters'][] = array('myClass', 'translateUrlParameters'); 

public function translateUrlParameters($arrGet, $strLanguage, $arrRootPage)
{
 echo $strLanguage;
}
```

Wie komm ich da jetzt an die Sprache des jeweiligen Items ran in Version 3?

```
$GLOBALS['TL_HOOKS']['changelanguageNavigation'][] = array('myClass', 'changelanguageNavigation');

public function changelanguageNavigation(ChangelanguageNavigationEvent $event)
{
 echo $strLanguage = $event->currentLanguage(); ??????
 $strNewAlias = 'test' . $strLanguage;
 $event->getUrlParameterBag()->setUrlAttribute('items', $strNewAlias);
}
```

Hab schon etliche Sachen probiert, aber nichts funktioniert. Und $event->navigationItem kann auch nicht abgefragt werden, weil es private ist :(

Ohne die Abfrage der Sprache kann ich die URL ja nicht anpassen.

Danke schon mal für eure Hilfe

**Comment by aschempp** [comment]
Did you read the documentation?
https://github.com/terminal42/contao-changelanguage/blob/master/docs/07-developers.md#rewriting-an-url-parameter
