### ISSUE TITLE
Shows only 9 articles / shortcuts

### ISSUE THREAD

**Issue by FuturaDink** [terminal42/contao-changelanguage#106]
Hi, the extensions shows 9 main articles / shortcuts, despite the fact that we have more than 20 articles so far.
![bildschirmfoto 2017-02-17 um 12 28 09](https://cloud.githubusercontent.com/assets/6049752/23133027/e580cb22-f78f-11e6-9bd5-40b1309d8977.png)

![bildschirmfoto 2017-02-17 um 12 30 42](https://cloud.githubusercontent.com/assets/6049752/23133017/dc8c8182-f78f-11e6-8584-70c0b90618f0.png)

Any hints / thoughts on this?

</tia>

**Comment by fritzmg** [comment]
Does this also happen if you disable the news_categories extension?

**Comment by FuturaDink** [comment]
Yes. Strange thing is, it works if i disable the changelanguage extension and enable newslanguage. Disabled newslanguage shows no effect.

**Comment by Toflar** [comment]
newslanguage is not needed with changelanguage 3. Just uninstall it, please. Why are there two fields named "Hauptbeitrag"?

**Comment by FuturaDink** [comment]
One came from "changelanguage", the other from "newslanguage". There is one now.

**Comment by FuturaDink** [comment]
![bildschirmfoto 2017-02-17 um 12 28 09](https://cloud.githubusercontent.com/assets/6049752/23211074/87fd9364-f900-11e6-901d-6994e8f810a1.png)

**Comment by FuturaDink** [comment]
![bildschirmfoto 2017-02-22 um 13 11 56](https://cloud.githubusercontent.com/assets/6049752/23211082/94a100c4-f900-11e6-97b7-436c8a703cee.png)

**Comment by stefansl** [comment]
I checked it in his backend. Disabling news-categories and newslanguage takes no effect on this issue. But: what I've seen, there are three news archives:

News (de only)
News (de)
News (en) _<-- connected to News (de)_

I don't know, if this affects the logic in changelanguage.

**Comment by Toflar** [comment]
Connecting happens via the redirect page. See the manual.

**Comment by aschempp** [comment]
There is actually nothing wrong here. The dropdown just shows articles that are not yet linked to anything. You can't link multiple news to the same entry from the master archive.
