### ISSUE TITLE
Database: tl_news_archive.master not found

### ISSUE THREAD

**Issue by Xendiadyon** [terminal42/contao-changelanguage#107]
Wenn wir changelanguage installieren und dann mehrere News-Archive anlegen und im Backend eines dieser News-Archive anlegen wollen, kommt der Fehler, dass das Datenbankfeld tl_news_archive.master nicht gesetzt ist.

Eventuell war das mal gesetzt, wurde aber durch die contao/install.php wieder entfernt.

Contao 3.5.24

**Comment by fritzmg** [comment]
Duplicate of #103
