### ISSUE TITLE
 Contao 3.5.19 Probleme mit Inhaltselementen bei ce-access

### ISSUE THREAD

**Issue by JensenR** [terminal42/contao-changelanguage#110]
Hallo, leider haben die Augensymbole zum sichtbar / unsichtbar machen keine Funktion bei installiertem ce-access. Wie kann der Fehler gelöst werden?

**Comment by fritzmg** [comment]
Duplicate of #101

**Comment by JensenR** [comment]
Aber ich benutze kein "changelanguage"...??

**Comment by Toflar** [comment]
Und warum machst du ein Ticket bei changelanguage?

**Comment by fritzmg** [comment]
Then why did you post this issue here? :wink:

**Comment by JensenR** [comment]
Mache dann mal ein neues auf ;-)
