### ISSUE TITLE
Changelanguage generiert zweifache URL bei Multidomain-Installation

### ISSUE THREAD

**Issue by Hotchili12** [terminal42/contao-changelanguage#111]
Ich habe eine mehrsprachige Seite mit Multidomains, domain.com (Hauptdomain), domain.de, domain.xy

![screen-01](https://cloud.githubusercontent.com/assets/26225491/23616472/208f0616-028a-11e7-84cd-5a55f6bbe28b.png)

![screen-02](https://cloud.githubusercontent.com/assets/26225491/23616481/29407754-028a-11e7-88c4-4156a905e09e.png)

Wenn man jetzt zu einer anderen Sprache wechselt, wird immer die aktuelle domain am Anfang des Links eingefügt, z.B. bei einem wechsel von domain.com nach domain.de:

http://www.domain.com/http://www.domain.de/produkte.html

Was kann man tun, dass die aktuelle domain nicht in die url eingebunden wird?
(changelanguage 3.1.2)

**Comment by aschempp** [comment]
Welche Contao-Version verwendest du?

**Comment by Hotchili13** [comment]
Contao 3.5.17

**Comment by fritzmg** [comment]
Wie bereits im Forum erwähnt solltest du zuerst auf Contao 3.5.24 aktualisieren und dann nochmal testen.

**Comment by Hotchili12** [comment]
Fehler besteht nach Update auf Contao 3.5.24 weiterhin

**Comment by Hotchili12** [comment]
Habe im template "nav_dropdown.html5"
"\Environment::get('base')." entfernt, jetzt geht es.

**Comment by fritzmg** [comment]
> Habe im template "nav_dropdown.html5"
> "\Environment::get('base')." entfernt, jetzt geht es.

Aus solchen Gründen habe ich dir im Forum auch eigentlich gesagt, dass du es zuerst mit einer neuen Contao Installation testen solltest 😉. Um eben Fehler durch Extensions (oder auch eigene Templates, wie in deinem Fall) auszuschließen.

**Comment by Hotchili12** [comment]
Es handelt sich hierbei um kein eigens Template sondern um ein Template das Bestandteil von Changelanguage ist (system\modules\changelanguage\templates\nav_dropdown.html5)

**Comment by fritzmg** [comment]
Ah sorry, da hatte ich mich verlesen.

**Comment by aschempp** [comment]
Fixed in ac2782b8707e22686569e917f21755b5b937bc50
