### ISSUE TITLE
Eigene Sprachtexte im Frontendmodul nicht nutzbar (Backend: Contao 4.3.5)

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-changelanguage#112]
Die Option "Eigene Sprachtexte" lässt sich im Contao-Backend beim Frontendmodul zwar aktivieren, es werden aber keine Eingabefelder angezeigt, welche die Eingabe der eigenen Sprachtexte ermöglichen:

![image](https://cloud.githubusercontent.com/assets/6831223/23649744/c9e3a2c2-031f-11e7-81b9-46eb32d9e07e.png)

**Comment by Toflar** [comment]
Wahrscheinlich Abhängigkeiten (Multicolumnwizard) nicht korrekt installiert?

**Comment by mpitz** [comment]
Vollkommen korrekt erkannt.

In der AppKernel.php fehlte die Regestrierung des Moduls Multicolumnwizard.

Danke!
