### ISSUE TITLE
Leider nochmal  Missing root page for language "en"

### ISSUE THREAD

**Issue by 47gn** [terminal42/contao-changelanguage#113]
Hallo zusammen,

haben eben im Issue https://github.com/terminal42/contao-changelanguage/issues/102 geschaut, das behandelt eigentlich den Fehler den ich eben bemerkt habe. Allerdings bin ich auf 3.1.2 Build 3 und unter Contao 3.5.24 und erhalte dennoch den Fehler. Ich rufe quasi die deutsche Version auf (Hauptdomain) und erhalte die Fehlermeldung, dass die Root Page für die Sprache Englisch fehlt. 

Irgendeine Idee? Oder kann ich konfigurationstechnisch noch was nachschauen? Ich betreibe ne eigene Erweiterung, welche sich aber hauptsächlich mit ContenElementen und FE-Modulen beschäftigt. Kann die hier irgendwie rein funken?

Danke schon mal im Voraus :)

**Comment by aschempp** [comment]
Die letzte Version dieser Erweiterung ist von 2014 (!!). Scheint als funktioniert sie mit Contao 3.5 nicht korrekt. Da wir sie selber nicht einsetzen kann ich leider keine Zeit für Bugfixes aufwenden. Ideal wäre du bezahlst einen Entwickler dafür den Fehler zu beheben, welcher die Anpassung dann per Pull Request zurückgeben kann :-)

**Comment by aschempp** [comment]
Ich kann das bei mir leider nicht reproduzieren. Kannst du mal den Code debuggen und herausfinden warum das passiert?

**Comment by felixpfeiffer** [comment]
Hallo, ich hänge mich hier mal ran.
Ich bekomme den Fehler ebenfalls.
Bei mir ist der Fall so, dass die englische Version der Seite vorerst noch nicht veröffentlicht werden soll.
Die Seitenstruktur ist aber schon vorbereitet, die Seiten zugewiesen etc.
Nun habe ich zusätzlich in den Seitenlayouts noch das Modul deaktiviert. Trotzdem kommt der Fehler.
Was muss ich denn noch alles abschalten, damit der Fehler nicht mehr kommt? Oder ist dieser Fall nicht vorgesehen?

**Comment by aschempp** [comment]
Should be fixed in 3524b77bda8e0d592c0ca585d1863ab3ff5fd686
