### ISSUE TITLE
News - im Unterarchiv keine Weiterleitung zu Seite und ext. URL möglich

### ISSUE THREAD

**Issue by Anke** [terminal42/contao-changelanguage#114]
Hallo,

ich habe unter News ein Hauptarchiv in englischer Sprache und ein davon abhängiges Archiv in deutscher Sprache. 

In englischen Newsartikeln kann ich auswählen, dass bei Klick auf "Weiterlesen" eine Weiterleitung auf eine Seite oder externe URL erfolgen soll. 
In den Artikeln des deutschen Newsarchivs kann ich nur "Standard" oder "Artikel" als Weiterleitungsziel auswählen; wenn ich auf "externe URL" klicke (weil ich auf eine interne Seite mit Ankerangabe verlinken muss), springt er zurück auf Standard oder Artikel, dasselbe passiert hier bei Anklicken der Option "Seite".

Gibt es dafür einen schnellen Workaround?

**Comment by fritzmg** [comment]
Wir konnten das Problem nicht reproduzieren.

* Contao 3.5.24
* Changelanguage 3.1.2
* PHP 7.1.1 & 5.6.21

@Anke deaktiviere sequentiell Extensions und prüfe, ob das Problem nach dem deaktiveren einer Extension nicht mehr auftritt.

**Comment by tsarma** [comment]
I have the same problem and able to trace it to extension `tags`  inside `tl_news.php`, just commented out effected lines.
