### ISSUE TITLE
Backend: Language-Switch verschwindet im paste-Modus

### ISSUE THREAD

**Issue by klauswagner** [terminal42/contao-changelanguage#115]
Wenn man im Backend ein Inhaltselement dupliziert oder verschiebt und somit in `&act=paste` (bzw. `&act=paste&mode=copy`) wechselt verschwindet der Sprachwechsler.

Fallbeispiel: Ich dupliziere ein Inhaltselement und will dieses in einem Artikel eines anderen Sprachseitenbaums ablegen muss ich den herkömmlichen (vergleichsweise umständlichen) Weg über die Artikelnavigation gehen.

**Comment by aschempp** [comment]
Das ist leider richtig, da Contao an dieser Stelle bisher keine Anpassungen ermöglicht :-(

**Comment by jankout** [comment]
@aschempp könntest du das bitte im Contao-Core-Team besprechen, damit das für alle Erweiterungen möglich ist? Das wäre klasse.

**Comment by aschempp** [comment]
Das Feature hat aktuell keine grosse Priorität für mich persönlich. Wenn du es dringend benötigst, versuche doch selber (oder über einen Entwickler deines Vertrauens) einen Pull-Request bei Contao zu machen der dafür eine Lösung bietet? 😊

**Comment by aschempp** [comment]
Fixed in version 3.2.3

**Comment by jankout** [comment]
Vielen lieben Dank!
