### ISSUE TITLE
Problem with multi-domain and changelanguage

### ISSUE THREAD

**Issue by iris2OnGitHub** [terminal42/contao-changelanguage#116]
We have a Contao-Installation Verion 3.5.25 with changelanguage 3.1.2 with 3 languages, DE the main language / fallback, IT and EN

Since we renamed the first page in the root "index" as it is advised, the changelanguage doesnt work properly anymore.
Example: http://www.paroli.info
With a german Browser it works, it does not if you try it with an e.g. EN-Browser. Then you can't get to the German root by clicking the icon. 

We read about naming all first pages in the 3 roots "index" which is only possible when you add the language to the URL. This would be an option but one with a lot of other consequences following ...
Is there another explanation for that error, do we do anything wrong? Do we have to make any other changes to make it work? 

Thanx a lot in advance ... 
Iris

**Comment by fritzmg** [comment]
> We read about naming all first pages in the 3 roots "index" which is only possible when you add the language to the URL. This would be an option but one with a lot of other consequences following ...

This is recommended, yes. Why do you not want to do that?

I don't think you can circumvent the problem any other way.

**Comment by iris2OnGitHub** [comment]
The Problem is that google doesn't like it that way, because it is a redirection and that might influence the google ranking :(

**Comment by fritzmg** [comment]
That is not true. A proper redirect will not influence the rank of a page in a negative way.

URLs that lead to a 404 error or simply redirect to the wrong content will be thrown out of the index or to a lower rank.

**Comment by iris2OnGitHub** [comment]
But Google shows it with a warning and "Weiterleitung", wenn I ask Google to check the page again ...

**Comment by iris2OnGitHub** [comment]
I check it on Google Webmaster Tools / Web Console and I add you a screenshot of the result, when I had it checked yesterday with all the index and the language added to the url. 

And I wouldn't like to risk an bad ranking of google ... I am sure it will affect it, don't you? 

![bildschirmfoto 2017-04-12 um 08 27 29](https://cloud.githubusercontent.com/assets/27287257/24944174/4784a072-1f5a-11e7-838e-5f9edd764a75.png)

**Comment by fritzmg** [comment]
This is just an info. 

Also you should enable __Rewrite URLs__ before you submit your sitemaps.

**Comment by iris2OnGitHub** [comment]
ah ok, thank you, I will try this ...

**Comment by iris2OnGitHub** [comment]
I did as you told me and I add you a screen of the result, still with a warning. Is this how it is supposed to be? 

![bildschirmfoto 2017-04-12 um 09 15 42](https://cloud.githubusercontent.com/assets/27287257/24945735/c1409e88-1f60-11e7-9155-867dc1f4c5b0.png)

**Comment by fritzmg** [comment]
Yes, this is how it is supposed to be.

Your sitemaps won't even contain http://www.paroli.info/, they will contain

* http://www.paroli.info/en/
* http://www.paroli.info/de/
* http://www.paroli.info/fr/

**Comment by iris2OnGitHub** [comment]
And you are sure this wont affect the google ranking? Thank you very much for you help so far, Fritz!

**Comment by fritzmg** [comment]
Yes, this is something completely normal.

Go to https://www.microsoft.com/ for instance, you will be redirected to your browser's language as well ;)
