### ISSUE TITLE
Insert Tags return null or empty

### ISSUE THREAD

**Issue by odait** [terminal42/contao-changelanguage#118]
Hi,

i have tried the insert tags like {{changelanguage_link_url::**ID**::en}} and {{changelanguage_link_name::**ID**::en}}. Both return null or empty. Could this be a bug?

Versions:
change_language: 3.1.3 Build 5
contao: 3.5.22

The FE-Module is activated and works correct!

Thank you

**Comment by odait** [comment]
Hi, 

i have posted a workaround: https://community.contao.org/de/showthread.php?66622-changelanguage-insert-tags&p=439601&viewfull=1#post439601

**Comment by aschempp** [comment]
Thanks! Fixed in 28caf11a2ef77aa5e5115a2b73caba49a8e04913

**Comment by scuben** [comment]
This bug breaks the insert tag feature completely and is found and fixed in early may. Now its july (2 months later). I think you need to tag a release to be able to use 3.1.4 with this fix included.

**Comment by aschempp** [comment]
3.1.4 has been released now
