### ISSUE TITLE
C4 backend Layout

### ISSUE THREAD

**Issue by Sioweb** [terminal42/contao-changelanguage#119]
Ho!

Im C4-Backend wird das Sprachwechsel-Icon zu groß ausgegeben. Evt hab ich es falsch installiert, bei mir sieht es aktuell so aus:

![screencapture-schmidt-immobilienhandel-loc-contao-1494832523365](https://cloud.githubusercontent.com/assets/1318048/26046461/4f01a82c-394f-11e7-8c28-0d55c6b80633.png)

Lg
Sascha

**Comment by aschempp** [comment]
Sicher dass du den Cache gelöscht hast?

**Comment by Sioweb** [comment]
Das prüfe ich gerade wie es aussieht werden bei mir Teile der Assets nicht geladen. Ich glaube das Problem liegt bei meiner Installation - sry :)

Ich schließe das Issue, ich versuche die Daten neu zu installieren.
