### ISSUE TITLE
Providing this Module as a Bundle

### ISSUE THREAD

**Issue by mvscheidt** [terminal42/contao-changelanguage#121]
Hello,

are there any plans providing this as a bundle in the near future (similar to the contao modules, I'm not expecting a full rewrite)?

We will be using this module in a project and will most likely fork and do the minimal required work to make this work as a "contao"-style bundle (so no changes unless necessary, e.g. I won't rewrite things into services) and we would provide a PR if you want to.

Of course this would break Contao 3.5 compatibility (which is the main reason it's not some sort of bundle yet, I guess?)

Best Regards,
Mike

**Comment by fritzmg** [comment]
Why do you need it as a bundle?

**Comment by aschempp** [comment]
There are no plans to rewrite this to a bundle as long as we support Contao 3. And there is also no reason to do so because Contao 3 extensions are perfectly compatible with Contao 4. Just require `terminal42/contao-changelanguage` in your Contao 4 Managed Edition and it will work out of the box 😎
