### ISSUE TITLE
Seite kann in Hauptsprache nicht ausgewählt werden

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-changelanguage#123]
Installation in 4.4 mit dem Contao Manager:
Wenn ich die passende Seite in der Hauptsprache aussuchen soll, kann ich diese nicht markieren. Die Checkboxen fehlen hier, der Button [Anwenden] wird nicht aktiv.

![grafik](https://user-images.githubusercontent.com/1299776/27650446-4ac71360-5c35-11e7-946c-a3fd7b07d244.png)

**Comment by aschempp** [comment]
das ist ein Contao Bug: https://github.com/contao/core-bundle/issues/883

**Comment by jankout** [comment]
Es taucht aber in 4.4.1 auf

**Comment by aschempp** [comment]
der DCA Picker ist in der 4.4.1 leider auch nicht nicht repariert (siehe https://contao.org/de/news/contao_4-4-1.html)

**Comment by jankout** [comment]
alles klar. Ich dachte mir das schon, dass es damit zusammenhängen muss. Danke. Viel Glück bei der Überarbeitung des DCA-Pickers. Ich freue mich auf die funktionierende Version.

**Comment by jankout** [comment]
Hallo Andreas, ich wollte noch fragen, ob eure Erweiterung erstmal angepasst werden muss, damit das wieder läuft? Ich habe heute die 4.4.2 installiert und auch wurde automatisch die neuste Version eurer Erweiterung geladen. Allerdings ist die Liste immer noch leer, wenn ich die Sprachversionen miteinander verknüpfen möchte.

**Comment by do-while** [comment]
Das hatte ich auch in der 4.4.2 trotz noch einmal gelöscht und neu installierter Changelanguage. Vorläufige Lösung war, dass man über "mehrere bearbeiten" die Seiten plötzlich zu sehen bekommt und man kann hier seine Seite markieren. Das klappt dann mit der Sprachumschaltung.
@terminal42: Irgendwie habt Ihr aber noch den falschen Modus im DCA!

**Comment by aschempp** [comment]
Contao 4.4.2+ is fixed in 3.1.6 (a15bb1c772845782c0004c9cca0fab42d4e37d1a)
