### ISSUE TITLE
No custom language texts input fields

### ISSUE THREAD

**Issue by agoat** [terminal42/contao-changelanguage#124]
Not sure of it's my installation or a bug in combination with contao 4.4.

In the settings for the changelanguage module I see no input fields when I check `Custom language texts`. Maybe it's a bug in the `multicolumnwizard`. It's the only extension using the multicolumswizard in my installation. 

I have a clean contao 4.4 standard-edition installation with only `contao-changelanguage` added.

**Comment by aschempp** [comment]
look like you're missing the dependencies (`multicolumnwizard`). Did you manually install?

**Comment by agoat** [comment]
Installed and updated with the composer. `multicolumnwizard` is present.

Will the `multicolumnwizard` be registered in contao automatically or do I have to add this in the `AppKernel.php`?

**Comment by Toflar** [comment]
If you use the Contao Managed Edition, automatically. If you don't, you have to add it to the kernel in the correct order, just like in any regular Symfony app.

**Comment by agoat** [comment]
> If you don't, you have to add it to the kernel in the correct order, just like in any regular Symfony app.

OK, looks like this is it. 
Sadly there is no documentation for the `multicolumnwizard` for contao 4.

I think the same applies to `contao-haste`?!

**Comment by fritzmg** [comment]
> Sadly there is no documentation for the multicolumnwizard for contao 4.
> 
> I think the same applies to contao-haste?!

This is nothing specific to multicolumnwizard. You have to do that with any extension.

**Comment by agoat** [comment]
> You have to do that with any extension.

You guys are absolutely right. My fault. These are the only contao 3 compatible extensions I use with the new contao 4. I have not thought far enough ;-)

**Comment by aschempp** [comment]
I would suggest to use the Managed Edition which takes care of this automatically 😉
