### ISSUE TITLE
Fehlerhafter Alternate-Link auf Nachrichten-Detailseiten

### ISSUE THREAD

**Issue by kuplar** [terminal42/contao-changelanguage#125]
Hallo,

ich bin bei ChangeLanguage 3.1.3 auf einen Fehler in der Ausgabe der Alternate-Links auf Nachrichten- und Event-Detailseiten gestoßen. Bei aktiviertem "Auto_Item" wird der Alternate-Link der aktuellen Seite mit .../seiten-alias.html statt .../seiten-alias/nachrichten-alias.html generiert.

Beispiel:
Auf der en-Version einer Webseite mit den Sprachen en und de sehen die Alternate-Links so aus: 
```
<link rel="alternate" hreflang="en" href="http://www.example.com/en/news/article.html">
<link rel="alternate" hreflang="de" href="http://www.example.com/de/aktuelles/artikel/nachricht1.html">
```

Richtig wäre:
```
<link rel="alternate" hreflang="en" href="http://www.example.com/en/news/article/news1.html">
<link rel="alternate" hreflang="de" href="http://www.example.com/de/aktuelles/artikel/nachricht1.html">
```

Das ist mir erst bei der Aktualisierung von ChangeLanguage in einer Contao 3.5.6 Installation aufgefallen. Das Verhalten konnte ich in einem frischen Contao 3.5.27 reproduzieren.

**Comment by aschempp** [comment]
Fixed in fd975be59ae570a2d3c243dde90b26a622574ec1
