### ISSUE TITLE
4.4.1: Keine Seiten im Popupfenster vorhanden

### ISSUE THREAD

**Issue by jankout** [terminal42/contao-changelanguage#126]
Hallo, 

ich weiß es nicht, ob das mit dem neuen DCA-Picker zusammenhängt. Auf jeden Fall werden mir keine Seiten im Popupfenster angezeigt, sobald ich die Sprachversionen miteinander verknüpfen möchte. 

<img width="938" alt="snimek obrazovky 2017-07-12 v 12 17 25" src="https://user-images.githubusercontent.com/3715050/28113469-f8042bc2-66fc-11e7-8905-6678f9224625.png">

**Comment by ameotoko** [comment]
I have the same problem. Have been waiting for Contao 4.4.1 to solve #122 but now we have no pages to select from at all...

**Comment by aschempp** [comment]
Duplicate of #123
