### ISSUE TITLE
4.4.1 Dialog "Seite in Hauptsprache" bleibt leer

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-changelanguage#127]
Im Contao 4.4.1 bleibt der Dialog "Seite in Hauptsprache" bleibt leer, es werden keine Seiten der Hauptsprache gelistet. In der Version 4.4.0 fehlte das Markierfeld (Contao bug) aber jetzt fehlt der Seitenbaum der Fallback-Language.

**Comment by Toflar** [comment]
Der Picker ist immer noch kaputt, siehe Ankündigung. Das ist immer noch ein Core Bug.
