### ISSUE TITLE
Contao 4.4 keine Hauptsprachzuweisung möglich

### ISSUE THREAD

**Issue by rorych** [terminal42/contao-changelanguage#129]
**Aufbau**
contao 4.4.1 standard-edition
changelanguage 3.1.4
zwei Startpunkte DE (Hauptsprache) und EN
DE ca. 15 Seiten
EN ein Startpunkt & eine Unterseite

Startpunkt EN - http://imgur.com/KA3WApN
Startpunkt DE - http://imgur.com/rfBFqgt
Modul Setup - http://imgur.com/d5rGfHi
Hauptsrachauswahl in der Unterseite EN - http://imgur.com/NzVUsHI

**Problem**
Beim verlinken der Unterseiten von EN zu der Hauptsprache DE erscheinen keine Seiten zur Auswahl

Mache ich etwas falsch oder ist das ein bekannter/neuer Bug?

Danke im Voraus

**Comment by aschempp** [comment]
Duplicate of #122
Duplicate of #123 
Duplicate of #126 
Duplicate of #127
Duplicate of #128 

It would be appropriate to use the search before creating new issues…
