### ISSUE TITLE
Edit multiple emits warning upon save

### ISSUE THREAD

**Issue by sleitz** [terminal42/contao-changelanguage#130]
Steps to reproduce (in Contao 4.4):

- Select two pages to edit
- Check
  - "Page name"
  - "Page in main language"
- Edit and select two corresponding pages
- Save

Result:

    Warning: implode(): Invalid arguments passed in /…/vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php on line 341
    
    Warning: implode(): Invalid arguments passed in /…/vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php on line 341

This continues for a long time (I suspect: one line for each existing page).

Is this a core bug or only affects changelanguage? If I only select "Page Name" the problem does not occur. But it still could depend on the widget type.

**Comment by aschempp** [comment]
I cannot reproduce this in the latest Contao 4.5. I think this was a core bug back in the days, possibly in the initial picker implementation.
