### ISSUE TITLE
In Nachrichten-Archiv kann nur "Dies ist ein Hauptarchiv" gewählt werden

### ISSUE THREAD

**Issue by SGehle** [terminal42/contao-changelanguage#131]
Hallo!
Ich habe 4 Nachrichten-Archive angelegt, leider kann ich immer nur "Dies ist ein Hauptarchiv" auswählen. Getestet unter Contao 4.4.2 und changelanguage 3.1.6

Woran kann dies liegen?

**Comment by aschempp** [comment]
Du hast wohl die entsprechenden Weiterleitungsseiten nicht verknüpft. Was in der 4.4.1 aufgrund des kaputten Pickers auch gar nicht geht, du musst erst auf Contao 4.4.2 aktualisieren 😉

**Comment by SGehle** [comment]
Danke für den Tipp, habe auf 4.4.2 aktualisiert und Weiterleitungsseiten aus verschiedensprachigen Seitenbäumen gewählt... gleiches Problem.

**Comment by fritzmg** [comment]
> und Weiterleitungsseiten aus verschiedensprachigen Seitenbäumen gewählt...

Was genau meinst du damit? Du musst die Weiterleitungsseiten der Archive korrekt konfigurieren und dann diese Seiten miteinander verknüpfen. Nur so kann changelanguage wissen, welches Newsarchiv zu welcher Sprache gehört.

**Comment by SGehle** [comment]
Ja, hatte ich soweit alles, Seiten waren ausgeblendet, nochmal Cache geleert, jetzt klappt alles. Danke! :-)
