### ISSUE TITLE
Cannot choose news master archive initially

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#133]
When you create a new news archive, your only option in __Master archive__ will always be _This is a master archive_. Only after setting the redirect page and saving the new news archive, you'll be able to choose the actual master archive.

I know this is a known limitation, since changelanguage 3 connects the news archives via their redirect pages.

But is this really necessary? What is the reason behind the new system - does it really matter whether the connection is made via the redirect pages or directly between the archives? Why not let the user choose the main archive directly here?

**Comment by aschempp** [comment]
This was possible in the previous version, but I find it confusing and wrong that you can setup incorrect relations. Also, if you have a lot of archives and languages that are not related, its much easier to select the correct archive.
