### ISSUE TITLE
Fatal error: You must not have more than one auto_item

### ISSUE THREAD

**Issue by operatorone** [terminal42/contao-changelanguage#136]
Hi, I just used the Version 3.1.6 with Contao 3.5.27 and when auto_item is active I get the following error:
```
Fatal error: Uncaught exception RuntimeException with message You must not have more than one auto_item parameter thrown in system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/UrlParameterBag.php on line 188
#0 system/modules/changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationItem.php(223): Terminal42\ChangeLanguage\Navigation\UrlParameterBag->generateParameters()
#1 system/modules/changelanguage/library/Terminal42/ChangeLanguage/Helper/AlternateLinks.php(61): Terminal42\ChangeLanguage\Navigation\NavigationItem->getHref(Object(Terminal42\ChangeLanguage\Navigation\UrlParameterBag))
#2 system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(92): Terminal42\ChangeLanguage\Helper\AlternateLinks->addFromNavigationItem(Object(Terminal42\ChangeLanguage\Navigation\NavigationItem), Object(Terminal42\ChangeLanguage\Navigation\UrlParameterBag))
#3 system/modules/core/modules/Module.php(287): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->compile()
#4 system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#5 system/modules/changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(50): Haste\Frontend\AbstractFrontendModule->generate()
#6 system/modules/core/library/Contao/Controller.php(321): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->generate()
#7 system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('5')
#8 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('\n
replace('...', false)
#11 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#12 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#13 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 index.php(20): Contao\FrontendIndex->run()
#15 {main}
```

Can you give me a hint how to fix this?

Cheers,
operatorone

**Comment by aschempp** [comment]
What extensions did you install?

**Comment by operatorone** [comment]
Hi, the following extensions are installed.

BackupDB / 3.2.2 / 17
ce_article_list / 1.7.0 / 2
changelanguage / 3.1.6 / 2
dcawizard / 2.3.4 / 12
Divider / 1.3.0 / 17
dk_masonry / 1.2.1 / 7
dk_mmenu / 1.5.1 / 7
dlh_geocode / 1.0.4 / 6
dlh_googlemaps / 2.2.0 / 3
easyFavicon / 1.0.2 / 6
easy_themes / 2.2.1 / 18
extended_checkbox / 1.1.3 / 6
faqextensions / 1.0.0 / 6
haste / 4.17.3 / 1
kit_fontawesome / 1.0.2 / 5
magnific_popup / 2.0.0 / 4
mobile_menu / 2.6.0 / 1
MultiColumnWizard / 3.3.6 / 4
multifileupload / 2.1.0 / 5
NamespaceClassLoader / 1.0.2 / 43
navigation / 3.5.0-beta1 / 9
notification_center / 1.4.0 / 5
onepage-navigation / 1.0.1 / 2
prosearch / 1.0.0 / 81
rocksolid-antispam / 1.0.3 / 16
rocksolid-columns / 1.0.6 / 16
rocksolid-custom-elements / 1.3.10 / 12
rocksolid-frontend-helper / 1.2.4 / 9
rocksolid-icon-picker / 1.0.7 / 16
rocksolid-slider / 1.6.2 / 7
sharebuttons / 1.3.5 / 4
slickmap / 1.2.1 / 1
SWGlossar / 4.4.5 / 2

**Comment by aschempp** [comment]
I can't see what the problem is in this list, but there must be two extensions handling the changelanguage event and being present on the same page. It's certainly not a bug in changelanguage, there's nothing I can do about it…

**Comment by rorych** [comment]
I know it's a old Issue, but i had the same issue and it looks like it's the "SWGlossar", that is causing the issue, Repo: https://github.com/Sioweb/Glossar-Contao-4

To test it, you can uncomment the line:
`Input::setGet('items', Input::get('auto_item'));`

in these files:
<img width="758" alt="auto_item" src="https://user-images.githubusercontent.com/2022054/77070470-8f8f0500-69ea-11ea-8b1b-bd79b48ea50c.png">
