### ISSUE TITLE
Do not set hreflang -tag for $targetPage of type "error_"

### ISSUE THREAD

**Issue by TomHell** [terminal42/contao-changelanguage#137]
I also recommend that pages of the type "**error_**" _should not get_ the hreflang - tag or in case to set a special "checkbox" to control that behavior by users in the page settings.

To achieve this goal for the moment I have added in NavigationItem.php in function setTargetPage(...) on line 139:

> #Do not handle/set $targetPage if it is a type of "error_*" page
`if(strpos($targetPage->type,'error_') !== false)`
`{`
`return;`
`}`

This is special for SEO.

Cheers

**Comment by TomHell** [comment]
Fix this behavior by TL_HOOK -> generatePage to set correct values for SEO optimization. This issue concerned "error_" pages and pages with "robots" => "noindex" value. So I close this issue.

**Comment by aschempp** [comment]
If you do not link the error pages, there would not be a href tag, right?

**Comment by TomHell** [comment]
Thanks for the tip, that is correct. If I do not link 404 pages, the hreflang-tag will not set. *perfect*

Do you have any ideas how to handle no-index or no-follow pages. They should not have hreflang-tags as well. I wrote my own method, because there are so many cases at my task.

**no tag for**
- noIndex pages

**tags for**
- news archive (1 language de_CH, but multi domains like fr_CH, en_CH, de_DE, at_CH) where I support only this blog in this one language "de_CH"
- pagination pages which should link on it self

I have got it work by my self. So I`m not sure if this cases are to special to implement this feature in the future.

**Comment by aschempp** [comment]
Please create separate issues for separate tasks. I'm not exactly sure what you mean with the pagination.
