### ISSUE TITLE
Fix onchange event so it works in IE and Edge

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-changelanguage#142]
As IE and Edge did not respect the base tag while fetching a relative URL from e.g. a href attribute. We have to put the base href as prefix to the location at least for IE and Edge. Otherwise change language with nav_dropdown will not work in IE and Edge.

https://github.com/terminal42/contao-changelanguage/blob/master/templates/nav_dropdown.html5#L18
```html
old
<select class="<?php echo $this->level; ?>" onchange="window.location.href=this.value">
new
<select class="<?php echo $this->level; ?>" onchange="window.location.href=document.getElementsByTagName(base)[0].getAttribute('href')+this.value">
```

**Comment by Toflar** [comment]
I think it's not needed to query the DOM to fetch the base. Can you try using `window.location.replace()`? It's better anyway :)

**Comment by fritzmg** [comment]
```php
<select class="<?php echo $this->level; ?>" onchange="window.location.replace(this.value)">
```
does not work unfortunately. Neither does
```php
<select class="<?php echo $this->level; ?>" onchange="window.location.assign(this.value)">
```

**Comment by Aybee** [comment]
@Toflar Why is replace() better? You remove the URL from history with replace(). I think this is not intended.

I don't know the difference between location.href and location.assign(), but fact ist, that we can **not** use `this.value` with IE and Edge, no matter which method we use, as this is missing the base.href in IE and Edge.

**Comment by Toflar** [comment]
> @Toflar Why is replace() better? You remove the URL from history with replace(). I think this is not intended.

True. I think there must be a different way than querying the DOM. The JS API certainly supports it, we just have to figure out what exactly Edge expects. I notices that it works by prefixing it with `/` and actually make it absolute -.-

**Comment by fritzmg** [comment]
[This](https://stackoverflow.com/a/632657/374996) suggests reading the href property of the base tag manually as well.

**Comment by Toflar** [comment]
Hmm, what if the base tag does not exist?

**Comment by fritzmg** [comment]
Then this will result in a JavaScript error 😁 

May the most complete solution is to always output absolute URLs whenever you need to set said URL via JavaScript.

**Comment by Toflar** [comment]
Yeah, absolute URL's in the template would be the easiest way in my opinion. @aschempp ?

**Comment by Aybee** [comment]
Other solution without querying the DOM.
```php
$GLOBALS['TL_HEAD'][] = '<script>baseref = "'.$this->base.'";</script>';
```
```html
<select class="<?php echo $this->level; ?>" onchange="window.location.assign(baseref+this.value);">
```
Untested, probably `$this->base` will not work here.

No problem if base does not exist.

ps Now I see that also other browser do not have the base.href with this.value but they respect it while using location.href or location.assign().

@Toflar you mean absolute URLs only in this select menu? Yes, I think this will be best solution.

**Comment by aschempp** [comment]
We should simply have absolute urls in the option value. Not sure how to accomplish that though, as the URL might already be absolute if on another domain.

**Comment by fritzmg** [comment]
You can use
```diff
-   $href = \Controller::generateFrontendUrl(
+   $href = $targetPage->getAbsoluteUrl(
-       $targetPage->row(),
        $urlParameterBag->generateParameters(), 
-       $targetPage->rootLanguage, 
-       true
    );
```
[here](https://github.com/terminal42/contao-changelanguage/blob/3.1.7/library/Terminal42/ChangeLanguage/Navigation/NavigationItem.php#L221-L226). However, this will obviously also affect the regular nav.

**Comment by aschempp** [comment]
Which is certainly not what we want …

**Comment by fritzmg** [comment]
Or you could prepend the `$item['href']` with
```php
<?= (stripos($item['href'], 'http') !== 0 ? \Environment::get('base') : '') . $item['href'] ?>
```
which isn't very elegant either.
