### ISSUE TITLE
Sprachwechsel Links werden über productdetails statt Kategorie geleitet.

### ISSUE THREAD

**Issue by EyeCatcher92** [terminal42/contao-changelanguage#149]
Hallo Zusammen,
der Sprachwechsler macht bei mir aktuell das Problem, dass er auf den Produktseiten über productdetails weiterleitet und nicht über den Kategorie Link.

So ist es aktuell: https://example.com/de/produkt-details/produktname.html
So soll es sein: https://example.com/de/kategoriename/produktname.html

Es sind sogar beide Varianten aufrufbar / erreichbar.
Die Frage nun wie kann ich hier den Sprachwechsler anweisen immer über die Kategorie zu gehen wenn eine vorhanden ist?

Das Problem breitet sich dann hier auch auf die alternative hreflang aus.

Forumseintrag: https://community.contao.org/de/showthread.php?70895-templates-block_alternate_links-html5-falsche-URL-im-Link

In verwendung:
Contao CMS 3.5.33
Isotope 2.5.1
changelanguage 3.1.9

**Comment by fritzmg** [comment]
Ein Produkt kann ja in mehreren Kategorien vorhanden sein.

**Comment by EyeCatcher92** [comment]
Stimmt. Aber ich müsste ja trotzdem (SEO) angeben, dass hier duplicate Content ist.
Somit bräuchte ich also die Links mit den Kategorien.

**Comment by fritzmg** [comment]
Fügt nicht Isotope ohnehin schon einen canonical Tag ein?

**Comment by EyeCatcher92** [comment]
Kann man das Problem nicht lösen in dem man hier genau jedem Produkt nur eine Kategorie zu ordnet. 

Ja, aber dieser Zeigt nur auf die aktuell besuchte Seite. Müsste dieser nicht genau auf die anderen Seiten zeigen?
