### ISSUE TITLE
Missing in documentation how to get the language parameter into the URL

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-changelanguage#150]
Es fehlt die Information, wie man das Sprachkürzel in die URL bekommt. Z.B. über die `app/config/parameters.yml`
```yml
parameters:
    prepend_locale: true
```

**Comment by Toflar** [comment]
Warum sollte das bei Changelanguage dokumentiert werden wo es doch ein Core-Feature ist?

**Comment by Aybee** [comment]
Nun ja, man installiert die Erweiterung und möchte sie dann ja auch nutzen. Und dies war mir nicht möglich, erst nach ca 1 Stunde suchen und mit Hilfestellung aus dem Forum. Deswegen wäre es doch gut, wenn z.B. hier in der Dokumentation die Anleitung zu finden wäre.

**Comment by Aybee** [comment]
Aber man könnte ja zumindestens auf dieser Seite https://github.com/terminal42/contao-changelanguage/blob/master/docs/02-basics.md einen Hinweis auf `parameters: prepend_locale: true` setzen, dass man nicht allzu lange danach suchen muss.

**Comment by Aybee** [comment]
Ja, ok, dies habe ich verstanden, aber wir sind es ja so gewohnt, dass wir in den Einstellungen immer den Haken bei "Die Sprache zur URL hinzufügen" gesetzt hatten, sobald changelanguage im Einsatz war. Und da diese Checkbox jetzt nicht mehr vorhanden ist, geht da wohl bei jedem erstmal die Sucherei los. Und um diese abzukürzen wäre ein Hinweis hier sinnvoll denke ich.

**Comment by fritzmg** [comment]
> sobald changelanguage im Einsatz war

Nochmal, das hat nichts mit changelanguage zu tun. Du setzt diese Option ja völlig unabhängig von changelanguage. Wenn deine Website mehrere Sprachen und nur eine Domain hast, verwendest du (sehr wahrscheinlich) diese Einstellung. Egal ob du changelanguage verwendest, oder nicht.
