### ISSUE TITLE
Sprachmenu wird auch ohne DirectFallback erzeugt

### ISSUE THREAD

**Issue by s6t** [terminal42/contao-changelanguage#151]
Wird im Modul "Hide langaudes without direct fallback" angewählt und es existiert kein direkter Fallback werden trotzdem die Headerlinks und das Sprachmenu erzeugt.

Dies könnte man umgehen, indem die Anzahl der Template Items geprüft wird.

```
if ($this->hideNoFallback && count($templateItems) < 2)
{
    return;
}
```

**Comment by aschempp** [comment]
Verwendest du die neuste Version? Denn das sollte bereits korrigiert sein (siehe https://github.com/terminal42/contao-changelanguage/pull/89 und https://github.com/terminal42/contao-changelanguage/commit/3b16e25971ebd4d8ecdb1c11ef535d9ed9b2914b)
