### ISSUE TITLE
Contao 4.6.3: target Problem

### ISSUE THREAD

**Issue by chriza** [terminal42/contao-changelanguage#153]
Hallo Zusammen,
in Contao 4.6.3 wird das target Attribut nicht richtig erzeugt und somit der Sprachwechsel stets in einem neuen Fenster ausgeführt.

![grafik](https://user-images.githubusercontent.com/1572887/45484657-1fe4ed80-b755-11e8-9314-e1dab49dad24.png)

**Comment by aschempp** [comment]
Hast du ein eigenes angepasstes Template?

**Comment by chriza** [comment]
Vielen Dank für den Tipp. Ich hatte ein Bootstrap Template unterlegt. Dieses führt zum Fehler.
