### ISSUE TITLE
rel="alternate" werden nicht angezeigt

### ISSUE THREAD

**Issue by bekanntmacher** [terminal42/contao-changelanguage#154]
Setzt man kein Sprachwechsler Menu in das Seitenlayout, werden die Verknüpfungen im Head nicht angezeigt.

**Comment by fritzmg** [comment]
Das ist auch so gewollt, denke ich.

**Comment by aschempp** [comment]
Korrekt. Das Modul übernimmt keine Funktionen wenn es nicht integriert ist 😉

**Comment by fritzmg** [comment]
> Mit einem leeren Template lässt es sich lösen, ist aber nicht so die feine Lösung...

Warum nicht? Genau das brauchst du ja. Sprachenwechsler ohne Ausgabe.

**Comment by bekanntmacher** [comment]
Es ist nicht notwendig, die Ausgabe der Links von der Navi abhängig zu machen, Punkt. Ich brauche nicht einen leeren sondern keinen Sprachwechsler, aber lassen wir das... lösen kann ich's, wollte nur das Modul verbessern...

**Comment by fritzmg** [comment]
> Es ist nicht notwendig, die Ausgabe der Links von der Navi abhängig zu machen, Punkt.

Die Ausgabe der alternate Tags ist nicht von der Navigation Abhängig sondern vom Modul.
