### ISSUE TITLE
Update composer requirement menatwork/contao-multicolumnwizard to menatwork/contao-multicolumnwizard-bundle

### ISSUE THREAD

**Issue by mathiassname** [terminal42/contao-changelanguage#158]
In composer.json is the requirement of "menatwork/contao-multicolumnwizard": "^3.3" . Why is this requirement in the composer.json? The problem is that it isn't possible to remove this requirement and use the newer "menatwork/contao-multicolumnwizard-bundle".

**Comment by fritzmg** [comment]
Why shouldn't it be there? The extension needs the MCW.

The new bundle has only been released recently. To allow a smooth transition, the new MCW version should have been released in the previous package imho, not a new package, since it tries to be fully backwards compatible.

**Comment by richardhj** [comment]
The `menatwork/contao-multicolumnwizard-bundle` replaces the `menatwork/contao-multicolumnwizard` which is defined in the composer.json respectively. It should just work, shouldn't it? 🤔 

https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/master/composer.json#L79
https://getcomposer.org/doc/04-schema.md#replace

**Comment by mathiassname** [comment]
If you run `composer require menatwork/contao-multicolumnwizard-bundle` it trigger the following error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install menatwork/contao-multicolumnwizard-bundle 3.4.0|remove menatwork/contao-multicolumnwizard 3.3.16
    - don't install menatwork/contao-multicolumnwizard-bundle 3.4.0|don't install menatwork/contao-multicolumnwizard 3.3.16
    - don't install menatwork/contao-multicolumnwizard-bundle 3.4.0|don't install menatwork/contao-multicolumnwizard 3.3.16
    - Installation request for menatwork/contao-multicolumnwizard-bundle ^3.4 -> satisfiable by menatwork/contao-multicolumnwizard-bundle[3.4.0].
    - Installation request for menatwork/contao-multicolumnwizard (locked at 3.3.16) -> satisfiable by menatwork/contao-multicolumnwizard[3.3.16].


Installation failed, reverting ./composer.json to its original content.
`

**Comment by fritzmg** [comment]
@richardhj good point

@mathiassname try
```
composer require menatwork/contao-multicolumnwizard-bundle --no-update && composer update -o --no-dev
```

**Comment by richardhj** [comment]
Does it work @mathiassname? We cannot jump over to the multicolumnwizard bundle as it is not compatible with Contao 3.
