### ISSUE TITLE
Multiple Changelanguage Modules in one page cause duplicate alternate Link Tags in header

### ISSUE THREAD

**Issue by mvscheidt** [terminal42/contao-changelanguage#159]
**Problem**

If you create two modules in contao backend (so you have two distinct IDs) and add them to the page via the layout for example, you will get the `alternate` Tags in the header twice.

Creating more than one module can be necessary if you want to have different styling / configuration so that reusing the same module twice (in which case the error does not occur) is not viable.

----

**Ideas**

One "simple" fix could be a new checkbox in the module configuration, which would allow the backend admin to disable generating the alternate Tags for certain modules.

Another way could be to rewrite the code a bit, so each entry is saved in a new entry of  `$GLOBALS['TL_HEAD']`

so instead of saving everything a string in one TL_HEAD entry like before

`$GLOBALS['TL_HEAD'][] = $headerLinks->generate();`

you would, loosely speaking, go for something more like this

```php
foreach($headerLinks as $headerLink) {
  if (!isset($GLOBALS['TL_HEAD'][$headerLink->someUniqueId])) {
     $GLOBALS['TL_HEAD'][$headerLink->someUniqueId] = $headerLink->generate();
  }
}
```

**Comment by aschempp** [comment]
I think we can fix this by just writing all header links into the same `$GLOBALS['TL_HEAD']['changelanguage_headers']` or thelike. Preferrably a key with a class constant. Haven't checked the code, but I hope they are all generated in the same place? 😇

**Comment by mvscheidt** [comment]
As far as I can see `$GLOBALS['TL_HEAD']` is only set here: https://github.com/terminal42/contao-changelanguage/blob/f7465d47021ffbca64d728f0da784ff136e36ff1/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php#L104

However wouldn't that solution cause issues when using the module config options `hideActiveLanguage` or `hideNoFallback`

Say I leave both boxes unticket for the first Module, and for the second I would tick both options.

Now depending on the order I add these to the frontend I would either have "all" alternate Links or some will be missing (the ones for active language and the languages without a fallback) I presume?

**Comment by richardhj** [comment]
The objections of @mvscheidt are justified. I decided to implement a singleton for the `AlternateLinks` class in c365d51, which however should be dropped in favor of a properly registered service once we drop Contao 3 support.

**Comment by aschempp** [comment]
Can we use a private static variable on the front end module instead of a singleton? I really came to dislike singletons 🙈

**Comment by richardhj** [comment]
@mvscheidt You are using a custom hook on `changelanguageNavigation`, aren't you?
Because Contao does an `array_unique()` on `$GLOBALS['TL_HEAD']` which means that having the alternate tags twice in the header really is an edge case.

> However wouldn't that solution cause issues when using the module config options `hideActiveLanguage` or `hideNoFallback`.

These two options do no influence the generated alternate tags, so that usually for two modules equal two alternate header blocks are generated, that later are parsed only once because of `array_unique()`.

**Comment by mvscheidt** [comment]
> You are using a custom hook on changelanguageNavigation, aren't you?

Yes, custom hook... ugh forgot to mention that. In my case this causes some items to be removed.

> These two options do no influence the generated alternate tags

The custom hook aside however, I assume this is because for normal pages the `continue` never gets triggered because `$item->isDirectFallback()` is always true?

I guess that's where I was confused then, because I assumed if you want to hide pages with the default module config `hideNoFallback` then the pages that don't have a fallback won't have a "DirectFallback" either.

https://github.com/terminal42/contao-changelanguage/blob/f7465d47021ffbca64d728f0da784ff136e36ff1/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php#L85-L93

Because if that continue in line 88 would be triggered then `$headerLinks->addFromNavigationItem` would not get called, thus we would be back to potentially having different header tags based on the config.
