### ISSUE TITLE
LabelCallback doesn't accept child_record_callbacks defined as an array

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-changelanguage#161]
I have defined a `child_record_callback` as an array (`['Class', 'method']`). Unfortunately `LabelCallback::register()` only accepts previous callbacks as being callables. Would it be possible to have support also for callback arrays?

https://github.com/terminal42/contao-changelanguage/blob/764854f733a3373ecf9be2d54518311bf2581f5a/library/Terminal42/ChangeLanguage/Helper/LabelCallback.php#L38-L40

If you agree, I could do a pull request.

**Comment by aschempp** [comment]
Arrays are supported, but only in a "Contao manner". See https://github.com/terminal42/contao-changelanguage/blob/764854f733a3373ecf9be2d54518311bf2581f5a/library/Terminal42/ChangeLanguage/Helper/LabelCallback.php#L76-L87

**Comment by Defcon0** [comment]
I see, but the `$this->previous` isn't even passed in if it's not a callable ;-)

https://github.com/terminal42/contao-changelanguage/blob/764854f733a3373ecf9be2d54518311bf2581f5a/library/Terminal42/ChangeLanguage/Helper/LabelCallback.php#L38-L40

I just tested it:

As a callable: working
As an array: not working

**Comment by aschempp** [comment]
Then your class name must be wrong or unresolvable. `is_callable` can handle arrays: https://www.php.net/is_callable

**Comment by Defcon0** [comment]
Ah, then I think I know what's wrong. I assign the callback via symfony service alias, i.e. (sorry for forgetting to mention this in the first post):

['acme.some.cool.alias', 'method']

I think core PHP can't handle this, right? But contao indeed can. So the simplest solution would be to do it like Contao does:

```
if (\is_array($callback))
{
	$this->import($callback[0]);
	$this->{$callback[0]}->{$callback[1]}($this);
}
elseif (\is_callable($callback))
{
	$callback($this);
}
```

**Comment by aschempp** [comment]
True, thats currently not supported (but sure should be).

**Comment by aschempp** [comment]
Could you create a pull request to fix this?

**Comment by Defcon0** [comment]
OK, now I have a bit time for that. I'll send a PR in no time.

**Comment by Defcon0** [comment]
OK, I created PR #162 for this.

**Comment by Defcon0** [comment]
@aschempp You accepted https://github.com/terminal42/contao-changelanguage/pull/162 . Could you please create a new tag for the fix? We need this for a project :-( Thanks!

**Comment by aschempp** [comment]
see https://github.com/terminal42/contao-changelanguage/pull/162

@Defcon0 will do asap!

**Comment by Defcon0** [comment]
Great, thanks!
