### ISSUE TITLE
Port is not included in link (Contao 4.7)

### ISSUE THREAD

**Issue by bytehead** [terminal42/contao-changelanguage#163]
**Affected version(s)**

3.1.11 with Contao 4.7.x

**Description**

The `href` of the change language link doesn't include any port from the origin uri.

**How to reproduce**

Run your installation on ~~the internal PHP server or with~~ the [symfony cli](https://symfony.com/doc/current/setup/symfony_server.html) on a specific port, like `https://127.0.0.1:8000`.

**Target state (example):** 
`https://127.0.0.1:8000/en`

**Actual state (example):**
`https://127.0.0.1/en`

**Update:**
Maybe it's just related to the symfony cli and/or cmf routing?

**Comment by Toflar** [comment]
Afaik we use `PageModel::generateAbsoluteUrl()`. Does your root page config include the port?

**Comment by bytehead** [comment]
Nope it doesn't and has never before. I think something changed with the introduced cmf router in Contao 4.7.

**Comment by aschempp** [comment]
Regardless of that, it must be a Contao core issue. Can you open an issue there?

**Comment by bytehead** [comment]
Hmm, Contao generates the urls correctly (with the port included). Sounds weird, but it is the case. I'll investigate a little bit more.

**Comment by bytehead** [comment]
It happens because of the `rootUseSSL` setting. Uses wrong port, if `rootUseSSL = false` but the page is requested via https (see also https://github.com/contao/contao/pull/350).

**Comment by bytehead** [comment]
So known limitation 🙂
