### ISSUE TITLE
Seite in Hauptsprache bleibt aktiv, wenn man Auswahl entfernt

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-changelanguage#164]
Fehler: Wenn ich einmal eine Seite in der Hauptsprache ausgewählt habe, bleibt sie aktiv, auch wenn ich später die "Auswahl entferne" und im Backend keine Seite mehr aufgeführt ist.
Die Klasse "nofallback" wird nicht vergeben, der deaktivierte Seintenlink bleibt bestehen.

Da ich mit _nofallback_ die Sprachen-Navigation ausblende, ist das in diesem Fall nicht möglich.

Abhilfe ist nur das Löschen der Seite und neues Anlegen einer Seite.

**Comment by aschempp** [comment]
Wie hast du die Auswahl entfernt?

**Comment by do-while** [comment]
In dem Popup gibt es ganz unten immer eine RadioBox "Auswahl entfernen", dann Speichern.
Im Backend ist dann auch kein Seitenlink mehr angegeben.

**Comment by aschempp** [comment]
Dann kann es eigentlich auch keine Verknüpfung mehr geben…

**Comment by do-while** [comment]
ja, dürfte nicht.

Man kann es reproduzieren:
1) Du hast eine Englische Seite (en + Fallback)
2) Du legst eine Deutsche Seite an, noch keine Verbindung machen: Dann hat die Sprachumschaltung auf der EN-Seite die Klasse nofallback
3) Jetzt definierst Du in der DE-Seite die Paarung mit der EN-Seite
4) Dann fällt die Klasse nofallback weg, da der Fallback für die Seite nicht benötigt wird.  => ist Ok
5) Jetzt entfernst Du die Auswahl bei der DE-Seite
6) Eigentlich müßte jetzt auf der EN-Seite wieder die Klasse nofallback erscheinen => tut es nicht

Kann es sein, dass das Datenbankfeld initial leer ist, später aber ein leeres Array da drin steht?
Dadurch würde es nicht als leer erkannt und damit wird die Klasse nicht ausgegeben
(ist nur eine Vermutung)

**Comment by richardhj** [comment]
Hi @do-while 
Danke für die Auflistung der Schritte, allerdings kann ich es nicht reproduzieren.
Ich bin auf Contao 4.4 und 4.7.
Schritte 1 bis 4 sind klar und nachvollziehbar.
Schritt 6 nicht, bei mir erscheint die CSS-Klasse "nofallback" wieder.

**Comment by do-while** [comment]
Ich habe es in einer neuen 4.4er Installation probiert, ich kann den Effekt hier auch nicht nachvollziehen.
Dann muss ich mal die Seite genau analysieren, wo der Effekt auftritt.

Sorry für den Fehlalarm - alles chic
