### ISSUE TITLE
Contao 4.7 - Error 500

### ISSUE THREAD

**Issue by Misco** [terminal42/contao-changelanguage#165]
Hello, after loading dev-master for my contao 4.7 i got an 500 Error at Installtool :(
I like this extension, always used =)

**Comment by richardhj** [comment]
Hosted on All-Inkl? Can you relate to https://github.com/terminal42/contao-notification_center/issues/168#issuecomment-469648726? Can you run the Install-Tool with app_dev.php?

**Comment by Misco** [comment]
then same error coming. seems similar issue, but what to do? All-Inkl. was always good the last years :(
i could install other extensions without problem.

**Comment by Misco** [comment]
well set memory limit higher worked so far. thx
