### ISSUE TITLE
Zuweisung von "Seite in Hauptsprache" wenn zuvor der Seitenbaum eingegrenzt wurde

### ISSUE THREAD

**Issue by Floxn** [terminal42/contao-changelanguage#166]
Hallo,

wenn in der Seitenstruktur z.B. nur der EN-Baum selektiert ist und die Hauptsprache zuweisen möchte wird die Sturktur der DE-Seite bei der Auswahl von "Seite in Hauptsprache" in den Eigenschaften nicht mehr angezeigt und kann nicht ausgewählt werden.

Nur die nicht-Hauptsprache ist selektiert:
<img width="241" alt="selektierter-Seitenbaum" src="https://user-images.githubusercontent.com/15326334/57516697-7a027680-7315-11e9-9809-08c8620aae5e.png">
Leere Auswahlmöglichkeit.
<img width="314" alt="leere-auswahl-bei-fuer-hauptsprache" src="https://user-images.githubusercontent.com/15326334/57516695-7a027680-7315-11e9-9144-5bd44fbb5274.png">

Lässt man in der Seitenstruktur wieder alle Seiten anzeigen ist es wieder möglich die Hauptsprache auszuwählen.

**Comment by richardhj** [comment]
Hier ein Screencast von meiner Installation.

![nc](https://user-images.githubusercontent.com/1284725/58933905-0ebb9100-8769-11e9-9534-c61609d524ed.gif)

Das klappt bei dir nicht? Kannst du das Problem genauer beschreiben?

**Comment by Floxn** [comment]
Das wie in deinem Video geht.
Nur bei der Zuweisung der Sprache nicht. 
![changelanguage](https://user-images.githubusercontent.com/15326334/58957953-0e8bb780-87a2-11e9-983f-0f2240ec100a.gif)
Man muss dann erst in der Auswahl bei "Seite in Hauptsprache" die Sprache wechseln um die Seite der Hauptsprache auswählen zu können.

Bei dieser Auswahl sollte doch direkt nur der Seitenbaum der Hauptsprache zu sehen sein.

Hoffe jetzt ist es verständlicher

**Comment by JensB74** [comment]
> 
> 
> Hier ein Screencast von meiner Installation.
> 
> ![nc](https://user-images.githubusercontent.com/1284725/58933905-0ebb9100-8769-11e9-9534-c61609d524ed.gif)
> 
> Das klappt bei dir nicht? Kannst du das Problem genauer beschreiben?

genau das was richardhj in seiner kleinen Animation zeigt klappt bei mir nicht, auch wenn ich die Sprache zuvor nicht eingeschränkt habe, also ich befinde mich auf der Hauptebene, klicke ich dann aber bei einem Artikel in eine andere Sprache, wird die Sprache nur beim ersten Mal gewechselt (deutsch nach englisch), beim zweiten Mal (englisch nach spanisch) bleibt sie in der aktuellen Sprache, gehe ich auf die Artikelübersicht ist dann aber auch die Sprache bis zum Artikel runter eingeschränkt und zwar in spanisch, nicht in englisch.

Bearbeitung in deutsch:
![1](https://user-images.githubusercontent.com/32700129/75450398-064a5c80-596f-11ea-8352-bf2fea216562.JPG)

Wechsel nach englisch:
![2](https://user-images.githubusercontent.com/32700129/75450431-15c9a580-596f-11ea-8dc5-914fe06982f8.JPG)
diese Ansicht bleibt auch wenn man auf spanisch wechselt, geht man dann in die Artikelübersicht ...

... sieht es in der Artikelübersicht so aus:
![3](https://user-images.githubusercontent.com/32700129/75450508-3f82cc80-596f-11ea-8e40-1026feb4f313.JPG)
hier würde ich jetzt eigentlich englisch vermuten, weil ja nicht nach spanisch gewechselt wurde.

Das überhaupt an dieser Stelle eingeschränkt wird ist auch doof, weil ich dann erst wieder auf "Alle" klicken muss ...

Installiert ist: Contao 4.9 mit Sprachenwechsler: 3.1.13
Provider: all-inkl.com, PHP 7.1

**Comment by jankout** [comment]
ich kann dieses FEhlverhalten bestätigen.

**Comment by aschempp** [comment]
Dieser Fehler sollte mit der neusten Version (3.2.3) behoben sein, könntet ihr das nochmals testen?
