### ISSUE TITLE
Falsche Links werden gesetzt, wenn ein News/Kalender Reader Modul vor Changelanguage geladen wird

### ISSUE THREAD

**Issue by c4y** [terminal42/contao-changelanguage#167]
Changelanguage: 3.1.11

Es gibt zwei Seitenbäume (de/en) mit je einem Event-Archiv (de/en) und jeweils eine Event-Liste samt Reader. Im folgenden Beispiel wird ein Event-Detail angezeigt (de), zu dem es kein bezogenes englisches Event gibt. Der Sprachenwechsler entfernt normalerweise den Alias und verlinkt auf die englische Seite

domain.de/de/event-liste/event-nur-de.html =>
domain.de/en/event-list.html

Wird aber das ModulEventReader vor dem Changelanguage geladen, wird der Alias "events" vom ModulEventReader als GET Parameter gesetzt, wodurch Changelanguage die URL inkl. Alias in jedem Fall generiert, was am Ende zu einem 404 führt. 

domain.de/de/event-liste/event-nur-de.html =>
domain.de/en/event-list/event-nur-de.html (404)

Es reicht ja schon, wenn Changelanguage als InsertTag z.B. in einem HTML Modul eingebunden wird. Dann wird es in jedem Fall nach dem ModulEventReader geladen. Gleiches gilt natürlich auch, wenn z.B. Changelanguage im Footer oder einfach im  Seitenlayout nach dem EventReader geladen wird.

Gleiches gilt natürlich für die News.

Man kann jetzt darüber streiten, ob man z.B. im Reader-Modul beide Archive (de/en) darstellt. Dann gibt es keinen 404, da auf der englischen Seite das deutsche Event angezeigt wird. Aber je nachdem wie ich Changelanguage einsetze, verhält es sich unterschiedlich.

**Comment by aschempp** [comment]
Closed in favor of https://github.com/terminal42/contao-changelanguage/pull/168
