### ISSUE TITLE
rel="alternate" auch für Hauptsprache

### ISSUE THREAD

**Issue by chromagnon** [terminal42/contao-changelanguage#169]
Hallo,

ich habe gerade changelanguage auf einer 3-sprachigen website im Einsatz. Der Kunde wollte gerne alternate hreflang Tags, so wie es Google empfiehlt. Die Empfehlung sieht vor, dass auf jeder Sprachversion alle möglichen Sprachversionen angegeben werden, nicht nur die anderen. Bei cangelanguage werden immer nur die Nebensprachen verlinkt, auch wenn man gerade auf einer ist. Also z.B.: fr ist Hauptsprache, es gibt alternate inks zu de und en. Bin ich auf en, gibts links zu de und en.
Evtl. gibt es dazu ja verschiedene Sichtweisen, der Kunde will natürlich Google gefallen und alles so haben, wie google es wünscht!?

Liebe Grüße

Chris

**Comment by fritzmg** [comment]
Wo steht diese Empfehlung?

**Comment by chromagnon** [comment]
https://support.google.com/webmasters/answer/189077?hl=de

**Comment by fritzmg** [comment]
Die changelanguage Extension macht das bereits.

**Comment by chromagnon** [comment]
Hallo,

ja, sie tut es, mein Fehler!!! Der alternate-Tag der Hauptsprache hing im Quelltext hinter dem vorherigen Tag, die beiden anderen Sprach-Tags standen dann einzeln pro Zeile. 
Also, alles OK, mein Flüchtigkeitsfehler! Vielen Dank für die Erweiterung und das Eingehen auf meine vermeintliche Fehlermeldung!
LG Chris
