### ISSUE TITLE
rel="alternate" auch ohne modul

### ISSUE THREAD

**Issue by chromagnon** [terminal42/contao-changelanguage#170]
Hi,

ich habe changelanguage nachträglich auf eine mehrsprachige website eingebunden, die einen "einfachen" Sprachwechsel hatte, der so auch OK ist, mir ging es nur um die Generierung der rel="alternate" hreflang tags. Die wollten aber partout nicht im Head auftauchen. Nur wenn auch ein Sprachwexhslermodul im Seitenlayout eingebunden ist, geht es. 
Wäre das entkoppelbar?

Liebe Grüße
Chris

**Comment by aschempp** [comment]
Aktuell nicht. Aber du kannst einfach ein leeres Template für das Modul anlegen, dann wird nichts angezeigt und die Tags ausgegeben 😉
