### ISSUE TITLE
lowercase language tag in URL 

### ISSUE THREAD

**Issue by reeLx** [terminal42/contao-changelanguage#171]
Is it possible to write the language tag in the url in lowercase letters?
For example: Our customer doesn't want the url named like this 

> https://www.domain.com/es-AR/

but instead like this

> https://www.domain.com/es-ar/

we tried to achieve that, by just renaming the tag into lowercase-letters in the backend module but that doesn't take any effect.

Greets
Marvin

**Comment by fritzmg** [comment]
This has nothing to do with this extension. This ticket belongs to https://github.com/contao/contao/issues
