### ISSUE TITLE
No page root in Multilanguage Domain

### ISSUE THREAD

**Issue by chriza** [terminal42/contao-changelanguage#172]
Contao 4.8.5

ich habe eine Multilanguage-Installation en / de (Fallback en).
in config/config.yml habe ich den Eintag:
contao:
 prepend_locale : true

Rufe ich die Domain mit einer nicht definierten Sprache auf wie
domain.tld/nl
erhalte ich die Frontend-Meldung "Diese Seite funktioniert nicht HTTP ERROR 500"
und im Systemlog: 
No root page found (host "domain.tld", language "nl")

Im core wird statt dessen eine 404 Seite geworfen:
contao.org/nl

**Comment by richardhj** [comment]
Ich glaube nicht, dass der Fehler "No root page found (host "domain.tld", language "nl")" zu dem Fehler 500 im Frontend gehört.
Kannst du bitte die Webseite im Debug-Modus aufrufen, um die passende Fehlermeldung zu dem Error 500 zu bekommen? (Backend, Klick auf "debug modus")
