### ISSUE TITLE
Ländererkennung de-De vs - de-CH

### ISSUE THREAD

**Issue by CBeck1818** [terminal42/contao-changelanguage#174]
Hallo,
ich habe momentan das Problem, dass die Länderkennung nicht seine gewünschte Funktion zeigt. Habe einen Strukturbaum mit der Kennung de-De und einen zweiten mit de-CH (auch nur mit ch schon probiert). Was passiert ist, dass immer die de-DE geladen wird, ebenso wenn ich die eindeutige Domainzuordnung eintrage. Bitte um Hilfestellung, Danke!

**Comment by richardhj** [comment]
Hast du `prepend_locale` in der Konfig aktiviert? 
wenn ja, rufst du die Website mit https://example.org/de-CH/ auf?

Wenn nein, rufst du die Webseite mit https://example.org/index-ch.html auf (wobei index-ch der Alias der Startseite des CH-Stammes ist)?

**Comment by fritzmg** [comment]
Das hat grundsätzlich nichts mit der Extension zu tun. Du solltest dein Problem auch eher zuerst in einem Community Forum Thread schildern und dort genauere Angaben über deine Contao Installation machen.
