### ISSUE TITLE
(Contao 4.4.46 ME) changelanguageNavigation-Hook wird nicht augeführt, hreflang wird nicht gesetzt.

### ISSUE THREAD

**Issue by amahnert** [terminal42/contao-changelanguage#175]
Hallo,

Ich versuche im Moment eine Contao Webseite auf eine andere Sprache zu übersetzen.
Am Ende sollen es zwei Webseiten  auf zwei verschiedenen Domains werden. Um die referenz zwischen zwei zusammengehörigen Seiten zu bilden und um nicht den ganzen Seitenbaum zu kopieren, sondern nur die Seiten die sich unterscheiden – habe ich mich entschieden das contao-changelanguage zu installieren/verwenden.

Das Problem ist nur, dass das contao-changelanguage nicht ganz funktioniert..
1. changelanguageNavigation-Hook wird nicht ausgeführt.
Den Code habe ich aus dem Doku-Beispiel genommen.
https://terminal42.github.io/contao-changelanguage/07-developers.html
![image](https://user-images.githubusercontent.com/3747959/72806563-b97bb380-3c55-11ea-9889-88c2a73c0fcf.png)

2.  hreflang wird nicht gesetzt. ( auch wenn languageMain gesetzt ist )
![image](https://user-images.githubusercontent.com/3747959/72806757-2000d180-3c56-11ea-852c-fdcd765a2ff8.png)

Laut app_dev.php sind changelanguage, haste, multicolumnwizard enabled.
![image](https://user-images.githubusercontent.com/3747959/72807335-791d3500-3c57-11ea-9cf3-569b1cf7f8e4.png)

Zusätzliche Informationen:
- contao/install wurde ausgeführt.
- es handelt sich um contao 4.4.46

Folgende Module sind installiert:
- codefog/contao-haste 4.24.3
- hschottm/tags
- RockSolid Custom Elements
- contao-multicolumnwizard 3.3.16
- nesbot/carbon
- terminal42/Change Language 3.1.13
- terminal42/Fine Uploader 

---

Mir gehen langsam die Ideen aus wie ich es debuggen kann. Ich vermute, dass der Inhalt der library Directory nicht geladen wird und ich habe aber leider gar keine Ahnung wie ich es überprüfen und/oder fixen kann.

Ich würde mich über jede Hilfe freuen.

LG
Aleksander M.

**Comment by aschempp** [comment]
> Um die referenz zwischen zwei zusammengehörigen Seiten zu bilden und um nicht den ganzen Seitenbaum zu kopieren, sondern nur die Seiten die sich unterscheiden – habe ich mich entschieden das contao-changelanguage zu installieren/verwenden.

Ich bin mir nicht sicher was du damit meinst? Contao und ChangeLanguage sind darauf ausgelegt, dass du den Seitenbaum duplizierst – ein andere Anwendungsfall ist nicht abgebildet. Ich denke nicht dass du das mit dem Hook/Event umgehen kannst, hast du das versucht?

**Comment by amahnert** [comment]
"Contao und ChangeLanguage sind darauf ausgelegt, dass du den Seitenbaum duplizierst"
- so habe ich es jetzt auch gemacht.  Problem gelöst.

Danke für deine Antwort. :)
