### ISSUE TITLE
Multi Column Wizard outdated

### ISSUE THREAD

**Issue by EnricoSchiller** [terminal42/contao-changelanguage#176]
Hallo! Leider funktioniert im multicolumnwizard der Picker seit der neuen Contao Version 4.8> nicht mehr. Eure Erweiterung nutzt diesen wizard aber noch was es immer schwierig macht das neue Bundle davon zu installieren:  https://github.com/menatwork/contao-multicolumnwizard-bundle

Wäre toll wenn ihr das require updaten würdet. Vielen dank!

**Comment by fritzmg** [comment]
@EnricoSchiller you need to run a full composer update, if you want to use `menatwork/contao-multicolumnwizard-bundle`. No change has to be made in `terminal42/contao-changelanguage`.

**Comment by aschempp** [comment]
Updated in a3a8359332ce765bb238f51161f3a7fb5f5aa203
