### ISSUE TITLE
Cannot get "main language page" on multidomain installation

### ISSUE THREAD

**Issue by klimeckt** [terminal42/contao-changelanguage#178]
I installed a multi-domain installation

In my site structure are

www.domain-englisch.de -> Language fallback EN
www.domain-german.de ->  Language fallback DE

I installed changelanguage Version 3.1.13 on contao 4.9.3 and see the "Keep query parameters" field only, means the "Main language page" button is missing. 

According to the manual, it's possible to link from the EN to the DE domain, vice versa. 

Do you have any suggestions? 

Best, Thomas

**Comment by havutcuoglu** [comment]
I have the same Problem with my installation.
The selector for "Main language page" is missing.

**Contao v4.9.3
Changelanguage v3.1.13**

Another problem is, if you add Domains in root page from Contao, the change language navigation is for the languages selection (navigation) is not there.

For example:
- root page DE
-- home

- root page EN
-- home

- root page TR
-- home

If the DNS settings has domain and language fallback in all root pages, then the source is empty.

If the DNS settings is empty (without domain and fallback) the change language navigation is there.
