### ISSUE TITLE
Probleme die Klasse zu laden.

### ISSUE THREAD

**Issue by Misco** [terminal42/contao-changelanguage#182]
Hallo,

ich habe eine Contao 4 Erweiterung in "src" folder.
Wenn ich in "Resources/contao/config/config.php" den hook eintrage bekomme ich die Meldung:

_Attempted to load class \"ChangelanguageNavigationListener\" from namespace \"Vendor\\Extension\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/html/dev/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php:211)"} []_

Wie bekomme ich die Klasse in dem Fall geladen? Danke

**Comment by fritzmg** [comment]
Für solche Fälle solltest du dich für Hilfe eher an die Contao Community wenden (Forum oder Slack).
