### ISSUE TITLE
Verarbeitung von auto_item

### ISSUE THREAD

**Issue by jxns** [terminal42/contao-changelanguage#183]
Hallo.

Ich verwende teilweise Unterseiten in Kombination mit \Input::get('auto_item').

Beispiel:
www.url.de/de/produkte/produkt123
Hier verwende ich das \Input::get('auto_item') um die Produkt-ID "produkt123" zu erhalten und mir intern dann im Template die Seite zu generieren.

Auf einer solchen Seite funktioniert jedoch der Sprachwechsel leider nicht. Hier würde ich gerne über den Sprachwechsel einfach von www.url.de/de/produkte/produkt123 auf www.url.de/en/produkte/produkt123 wechseln können.
Über die Erweiterung wird der Sprachwechsel-Link jedoch nur bis zu diesem hier verarbeitet: www.url.de/en/produkte

Lässt sich die Verarbeitung der auto_items in die Linkgenerierung noch mit aufnehmen?

**Comment by fritzmg** [comment]
See https://github.com/terminal42/contao-changelanguage/blob/main/docs/07-developers.md#supporting-changelanguage-in-custom-modules

**Comment by jxns** [comment]
Danke für die Info!
Ich habe den listener, wie angegeben, in  der config in meinem Bundle registriert:

`$GLOBALS['TL_HOOKS']['changelanguageNavigation'][] = [
    'Vendor\Extension\EventListener\ChangelanguageNavigationListener',
    'onChangelanguageNavigation'
];`

Hier erhalte ich nun allerdings die folgende Fehlermeldung:
`request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "ChangelanguageNavigationListener" from namespace "Vendor\Extension\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/vhosts/pagefolder/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php line 248 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Attempted to load class \"ChangelanguageNavigationListener\" from namespace \"Vendor\\Extension\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/vhosts/pagefolder/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php:248)"} []`

Habe ich hier etwas übersehen?

**Comment by fritzmg** [comment]
You are not supposed to use the namespace `Vendor\Extension`, that is just an example ;). Also see the official developer documentation on how to implement Hooks in Contao: 

* https://docs.contao.org/dev/getting-started/starting-development/
* https://docs.contao.org/dev/getting-started/hooks/
* https://docs.contao.org/dev/framework/hooks/

**Comment by jxns** [comment]
What would be the correct way to set the right namespace? I also tried it with the namespace to my Bundle and created the onChangelanguageNavigation file: `'src\MyBundle\EventListener\ChangelanguageNavigationListener',
      'onChangelanguageNavigation'`

but that also doesn't work

**Comment by fritzmg** [comment]
See the official documentation. If you implement this hook just for your application, then the FQCN of your hook class would be

```
App\EventListener\ChangelanguageNavigationListener
```

for example.

**Comment by jxns** [comment]
Yes, I am using this only for my application, but i still get the same error.

**Comment by aschempp** [comment]
I assume this can be closed because the issue is stale.
