### ISSUE TITLE
Probleme bei Seitentiteln mit Anführungszeichen ""

### ISSUE THREAD

**Issue by minstyle** [terminal42/contao-changelanguage#186]
**Contao 4.9.7
terminal42/contao-changelanguage 3.1.14**

Wenn ein Seitentitel Anführungszeichen beinhaltet, dann werden diese Zeichen nicht im title-Attribut des generierten Links "escaped" und der Quellcode ist dementsprechend nicht mehr W3C-konform.

Beispiel für einen Seitentitel:

`Ich bin ein Seitentitel mit "Anführungszeichen"`

Ausgabe im Frontend von _nav_changelanguage.html5_:

`<a href="https://www.domain.de/de/xyz"  title="Ich bin ein Seitentitel mit "Anführungszeichen"" class="lang-de active first" hreflang="de" lang="de" itemprop="url">`

**Comment by aschempp** [comment]
es gibt in dieser Erweiterung kein `nav_changelanguage.html5` Template?

**Comment by minstyle** [comment]
> es gibt in dieser Erweiterung kein `nav_changelanguage.html5` Template?

Das stimmt.

Ich verwende das Modul-Template `mod_changelanguage.html5` in Kombination mit dem leicht abgeänderten Navigations-Template von `nav_default.html5`.

Wobei `nav_default.html5` bei mir `nav_changelanguage.html5` heißt und folgenden Quelltext aufweist:

```
<ul class="<?= $this->level ?>">
	<?php foreach ($this->items as $item): ?>
		<?php if ($item['isActive'] || $item['isTrail']): ?>
			<li<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?>>
				<a href="<?= $item['href'] ?: './' ?>" title="<?= $item['pageTitle'] ?: $item['title'] ?>"<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?><?php if ($item['accesskey'] !== '') echo ' accesskey="' . $item['accesskey'] . '"'; ?><?php if ($item['tabindex']) echo ' tabindex="' . $item['tabindex'] . '"'; ?><?php if ($item['nofollow']) echo ' rel="nofollow"'; ?><?= $item['target'] ?><?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?> itemprop="url"><strong itemprop="name"><?= $item['link'] ?></strong><?php if (!empty($item['subitems'])) : ?><?php endif; ?></a><?= $item['subitems'] ?>
			</li>
		<?php else: ?>
			<li<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?>>
				<a href="<?= $item['href'] ?: './' ?>" title="<?= $item['pageTitle'] ?: $item['title'] ?>"<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?><?php if ($item['accesskey'] !== '') echo ' accesskey="' . $item['accesskey'] . '"'; ?><?php if ($item['tabindex']) echo ' tabindex="' . $item['tabindex'] . '"'; ?><?php if ($item['nofollow']) echo ' rel="nofollow"'; ?><?= $item['target'] ?><?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?> itemprop="url"><span itemprop="name"><?= $item['link'] ?></span><?php if (!empty($item['subitems'])) : ?><?php endif; ?></a><?= $item['subitems'] ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>
```

**Comment by aschempp** [comment]
mit der Funktion `specialchars()` kannst du die Zeichen entsprechend encodieren. Ich versteh aber noch nicht welchen Einfluss hier die Erweiterung hat, bzw. ob das ein Bug sein soll?

**Comment by fritzmg** [comment]
> Ich versteh aber noch nicht welchen Einfluss hier die Erweiterung hat, bzw. ob das ein Bug sein soll?

It leads to the following invalid HTML markup:

```html
<nav class="mod_changelanguage changelanguage block" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
  <ul class="level_1">
    <li class="lang-en first last"><a href="https://www.example.com/en/exhibitions-program" title="Lorem "Ipsum"" class="lang-en first last" hreflang="en" lang="en" itemprop="url"><span itemprop="name">English</span></a></li>
  </ul>
</nav>
```

The special characters need to be converted here I think:

https://github.com/terminal42/contao-changelanguage/blob/38ab7bed801a7dcf39d7bc4f8bbaa6a5a5b0b04d/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php#L140

**Comment by aschempp** [comment]
Fixed in aef893482936716f069661f5c996728f32cd8a22
