### ISSUE TITLE
Book navigation - Reference page

### ISSUE THREAD

**Issue by lionel-m** [terminal42/contao-changelanguage#19]
If a module requires a reference page, it will not be considered in the multilingual management.

For example, I have two languages FR + DE.

With the book navigation : 
![capture decran 2013-09-01 a 14 33 26](https://f.cloud.github.com/assets/814476/1063992/d11e156a-1302-11e3-8f72-5cc277711a95.png)

Then I insert my module in a page layout. If I switch in German, my module will no longer work. I have to create two modules and two page layouts...

It would be nice if the extension takes into account the reference pages.
In this case : `inhaltsverzeichnis.html`.

Thanks

**Comment by Aybee** [comment]
I'm missing this also now and z_modulealias seems not to be compatible with contao 3.4.3. Maybe you changed your mind and will implement it now.

Hallo Andreas,

ich habe eine Site mit mehreren Sprachen und ein normales Navigationsmodul welchem ich eine Referenzseite zuweise. Ich wünschte mir in diesem Navigationsmodule eine Checkbox "Respect fallback pages". Das würde sehr vieles vereinfachen. Auch für die individuelle Navigation könnte ich mir diese Checkbox vorstellen.

Bist du noch immer so absolut dagegen?

**Comment by aschempp** [comment]
Ja bin ich. Das ist keine Aufgabe dieser Erweiterung. "ChangeLanguage" bedeutete ja "Sprache wechseln" und nicht "Menü anhand der aktuellen Sprache anzeigen".
Es gibt mehrere Erweiterungen die zusätzliche Funktionen für Navigationen zu Verfügung stellen, eventuell kann das ja eine davon.

**Comment by Aybee** [comment]
Schade. Wäre das dann ein Feature für Contao? Denn die normale Navigation **ohne** Referenzseite orientiert sich ja an dem aktuellen Sprachbaum.

Ich mache erstmal weiter mit Navi-Modulen für jede Sprache und dann ein HTML-FE-Module mit
```html
<!-- indexer::stop -->
{{iflng::de}}{{insert_module::23}}{{iflng}}
{{iflng::es}}{{insert_module::24}}{{iflng}}
<!-- indexer::continue -->
```

**Comment by lionel-m** [comment]
> Schade. Wäre das dann ein Feature für Contao?

I am definitely for adding a issue into the core repository. The current system is not optimal. We need to duplicate modules for translations purpose e.g. `news list (fr)`, `news list (de)`, etc. For the form too e.g. `search (fr)`, `search (de)`, etc. And the HTML module as in your example. Too cumbersome...

It would be nice if we can make a connection between the forms and if the page pickers take into account our different languages.

**Comment by Toflar** [comment]
Which is something you should add to the contao tracker, not the changelanguage one :)

**Comment by Aybee** [comment]
https://github.com/contao/core/issues/7624 only regarding the navigation mudules

**Comment by frontendschlampe** [comment]
Ich bin mir nicht sicher, ob das Feature, wie z.B. https://github.com/contao/core/issues/7624 in den Core gehört, da es ja auf die Funktionalität einer Erweiterung aufbaut. Grundsätzlich kann Contao selbst keine Verbindung zwischen Modulen/Seiten und verschiedenen Sprache herstellen. Wenn wir dann endlich mal dazu kommen (was hoffentlich die nächsten Tage soweit sein sollte) die https://github.com/contao-community-alliance/language-relations für changelanguage 3 fertig zu machen, dann gibt es mit https://github.com/backbone87/contao-mod-article-translated eine Möglichkeit, Inhalte bestimmter Seiten abhängig von der Sprache mit nur einem Layout einzuarbeiten. Eventuell könnten wir in weiteren Entwicklungsschritten ggfs. weitere Funktionalitäten einarbeiten.
