### ISSUE TITLE
Allow selection for already selected pages in the page tree

### ISSUE THREAD

**Issue by havutcuoglu** [terminal42/contao-changelanguage#190]
Hello Terminal42,

under Contao 4.9 it is the case that already selected pages in the main language cannot be assigned to another page.
If I have two different pages, which in turn should redirect to one page in the main language, I can't do it.
Is it possible to remove this restriction so that we can assign any number of pages to a specific page?

Thanks a lot.

![selection-exist](https://user-images.githubusercontent.com/11348417/100727418-7d14fa00-33c6-11eb-9e71-29fd5e180494.png)

**Comment by fritzmg** [comment]
That won't work, because then the connection the other way around is ambiguous.

**Comment by havutcuoglu** [comment]
Yes you are right. 👍 
But can we not make it that works?
Any option, for example checkbox to say this is not the right page, don't take this page or how ever. :)

**Comment by fritzmg** [comment]
Not sure what you mean. For your use case, simply create a page in the main language as an internal redirect to the other one.
