### ISSUE TITLE
Sprache änderung von PHP / template

### ISSUE THREAD

**Issue by robvis** [terminal42/contao-changelanguage#194]
I'm looking for changing the language using PHP in my template.
I didn't find any changeable inserttag for switching form e.g. "de" to "en" using PHP.

Please could anyone help me out?

**Comment by fritzmg** [comment]
That's not what this extension is for. This extension allows you to assign pages (and news articles etc.) to a primary language pendant and provides a front end module which will allow you to switch between different language versions of particular pages/urls.

I am not really sure what you actually want to do, may be you should post on the Contao community forum (or in the community slack) and provide detailed information of your requirements and goals.

**Comment by robvis** [comment]
Hi Fritz,
I want to switch to another page language from PHP/template. So e.g. next page should be another language depending on personal data from a read db record.

**Comment by fritzmg** [comment]
So you want to override a page's output language dynamically? This has nothing to do with this extension. You should may be ask on the Contao community forum (or in the community slack) for help.
