### ISSUE TITLE
Type error when using InsertTag for non-existing page

### ISSUE THREAD

**Issue by bennyborn** [terminal42/contao-changelanguage#195]
If you use the InsertTag e.g. `{{changelanguage_link::15::fr}}` and there is no page with ID 15 or no version of the page for the specified language `Terminal42\ChangeLanguage\PageFinder::findAssociatedForLanguage` will throw an error because `$currentPage` is null and null is not of type `PageModel`.

![fatal](https://user-images.githubusercontent.com/226890/121007439-53cc9080-c792-11eb-905d-bb67b308e603.png)

**Comment by aschempp** [comment]
Thanks! Fixed in da7470aed29ded8d33d479c4697ab32e63669b7f (3.1.17)
