### ISSUE TITLE
Fehler bei verschachtelnden Insert-Tags im Backend

### ISSUE THREAD

**Issue by mwoelke** [terminal42/contao-changelanguage#196]
Ein verschachtelter Insert-Tag wie z.B.

`{{changelanguage_link_url::1::{{page::language}}}}`

wirft im Backend einen Fehler, weil changelanguage wohl Insert-Tags auch im Backend auflösen möchte. `{{page::language}}` ist im Backend aber nicht gefüllt, weswegen der Fehler geworfen wird `'' is not a supported language format`.

Ich hab das nun temporär gefixt indem ich am Anfang von `InsertTagListener::onReplaceInsertTags` auf TL_MODE geprüft habe, zeitgemäß ist das natürlich aber nicht.

**Comment by aschempp** [comment]
Inserttags werden im Backend (standardmässig) nicht ersetzt, da muss dir eine Erweiterung in die Quere kommen…
