### ISSUE TITLE
Nach der Plugin-Installation HTTP ERROR 500 

### ISSUE THREAD

**Issue by Cleanerrr** [terminal42/contao-changelanguage#197]
Hallo,
nach der Plugin-Installation und dem Ausführen von "Install tool" erhalte ich ein Fehler 500!

Fehler von Console nach "vendor/bin/contao-console cache:clear --no-warmup":
`You have requested a non-existent parameter "kernel.root_dir". Did you mean
   one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir"
  , "kernel.logs_dir"?
`

Contao 4.11.8
PHP: 7.4.19

Ist das ein Symfony Fehler, oder...?

Danke im Voraus

**Comment by webmurkser** [comment]
habe bereits ein Problem "vor" dem Install-Tool bei der aktualisierung auf die Version 3.2.0 von 3.1.17.

Contao: 4.9.19
PHP: 7.4.19
Hoster: all-inkl

Komplette-Konsolenausgabe (contao-manager 1.44) im Anhang. 
[konsole.txt](https://github.com/terminal42/contao-changelanguage/files/7014362/konsole.txt)

**Comment by fritzmg** [comment]
@Cleanerrr are you sure this is related to `terminal42/contao-changelanguage`? Check with `composer show menatwork/contao-multicolumnwizard-bundle` which version of the MCW is installed on your system. If it is `3.4.0`, then you are running into [this problem](https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107#issuecomment-900984313), which is not related to `terminal42/contao-changelanguage`.

@webmurkser your error is something else and also not directly related to `terminal42/contao-changelanguage`. Run a full package update again.

**Comment by webmurkser** [comment]
@fritzmg How should I start a "full-package" update via the contao manager except as before via "update"? 
Just with another module (terminal42/contao-easy_themes (2.2.11)) - was not installed before, works without problems.

**Comment by fritzmg** [comment]
> @fritzmg How should I start a "full-package" update via the contao manager except as before via "update"?

Via system maintenance. But the point is not _how_ you start it, but that you simply have to do it again, as your error is related to composer and likely just temporary. If you need more help you can use the community forum or community Slack.

**Comment by Cleanerrr** [comment]
> @Cleanerrr are you sure this is related to `terminal42/contao-changelanguage`? Check with `composer show menatwork/contao-multicolumnwizard-bundle` which version of the MCW is installed on your system. If it is `3.4.0` then you are running into [this problem](https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107#issuecomment-900984313), which is not related to `terminal42/contao-changelanguage`.
> 
> @webmurkser your error is something else and also not directly related to `terminal42/contao-changelanguage`. Run a full package update again.

With: composer show menatwork/contao-multicolumnwizard-bundle , I received next:

`[InvalidArgumentException]
  Package menatwork/contao-multicolumnwizard-bundle not found`

**Comment by fritzmg** [comment]
> With: composer show menatwork/contao-multicolumnwizard-bundle , I received next:
> 
> `[InvalidArgumentException] Package menatwork/contao-multicolumnwizard-bundle not found`

Which version of `terminal42/contao-changelanguage` do you have installed now?

**Comment by Cleanerrr** [comment]
I have this problem with the last version.
Contao installation is also fresh, from yesterday. Completely new project.

**Comment by webmurkser** [comment]
I have already tried the installation yesterday. With the same result. Today also already 2 times, the first time I did not have the console output - so I started it again a short time later. 

Is it possible that the package which is downloaded is defective? Why is there an error message that UNZIP cannot find the package?

**Comment by fritzmg** [comment]
> Why is there an error message that UNZIP cannot find the package?

It's a temporary error on your environment. It is not related to the package itself.

**Comment by fritzmg** [comment]
> I have this problem with the last version.

So if you execute `composer show terminal42/contao-changelanguage` it shows `3.2.0`? Because that should not be possible, as `terminal42/contao-changelanguage: 3.2.0` requires `menatwork/contao-multicolumnwizard-bundle`:

https://github.com/terminal42/contao-changelanguage/blob/28c3966cc8d8f6762b71c6474f84417fc2e0b977/composer.json#L32

**Comment by Cleanerrr** [comment]
I understand. But when I install terminal42/contao-changelanguage package, and try to run "install tool", I have Error 500. I didn't install separately menatwork/contao-multicolumnwizard-bundle ever. Should I with the new version?

**Comment by webmurkser** [comment]
> as your error is related to composer and likely just temporary. 

I have not had so far - and other modules can also be installed without any problems. I'll try it again later (just executed again - same result)

**Comment by fritzmg** [comment]
> I understand. But when I install terminal42/contao-changelanguage package, and try to run "install tool", I have Error 500. I didn't install separately menatwork/contao-multicolumnwizard-bundle ever. Should I with the new version?

You run into this error, because you are getting an outdated version of `menatwork/contao-multicolumnwizard-bundle` installed. See the issue that I have already linked for more details and for a workaround.

**Comment by Cleanerrr** [comment]
> > I understand. But when I install terminal42/contao-changelanguage package, and try to run "install tool", I have Error 500. I didn't install separately menatwork/contao-multicolumnwizard-bundle ever. Should I with the new version?
> 
> You run into this error, because you are getting an outdated version of `menatwork/contao-multicolumnwizard-bundle` installed. See the issue that I have already linked for more details and for a workaround.

You were right. It works. 
Temporary, I set the "conflict" in composer.json:
`    "conflict": {
        "menatwork/contao-multicolumnwizard-bundle": "<3.4.11",
        "menatwork/contao-multicolumnwizard": "<3.3.4"
    }`
Thanks

**Comment by webmurkser** [comment]
Wenn sich das erledigt hat, dann schließt hier. Ich erstelle ggf. neu.
