### ISSUE TITLE
Add link hreflang to generated pages

### ISSUE THREAD

**Issue by intco** [terminal42/contao-changelanguage#2]
Hi,

  a nice feature will be to automatically add the

``` html
<link rel="alternate" hreflang="..."  href="..." />
```

tag in the generated pages that have a translated version.

take a look at http://www.w3.org/TR/html401/struct/links.html#adef-hreflang

**Comment by justinwasilenko** [comment]
I have this extension installed on one of my sites, and it is not automatically adding the <link rel="alternate" hreflang="..."  href="..." />.
I have it installed on 2 other sites and it works as it is supposed to.
Running the latest version of the plugin (2.2.8) and Contao 3.5.2.
Link to the site: http://www.topp-textil.com/de/
