### ISSUE TITLE
Language switcher missing if copying records

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-changelanguage#207]
Hello,

I'm currently translating a large website. Thanks to this bundle we have the language switcher in the backend (in the article views):

![screen](https://user-images.githubusercontent.com/1485098/135982265-e7c1d9b2-03dd-465a-8e7c-94e3d07fcb7e.png)

Unfortunately, when I then copy a record in order to paste it in the translated article, this switcher is missing.

Is it a bug?

Thanks!

**Comment by fritzmg** [comment]
Might be related to #206

**Comment by Defcon0** [comment]
Interestingly this only happens if I copy a single object. When copying multiple ones, it works :-)

**Comment by aschempp** [comment]
fixed in e1ef27e0b48af71c7e674b16f07502a0bb5fca9e
