### ISSUE TITLE
status icon in articles

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-changelanguage#208]
There is a status-icon for every page that has no page in a fallback-language asigned and the same applies to news-items. https://terminal42.github.io/contao-changelanguage/02-basics.html#quickly-see-your-page-status
Im not sure if this has ever been the case for articles but currently there is **none** and i am missing it.

**Comment by aschempp** [comment]
there should be an icon if you have more than one article in the same column. If you don't then you don't need to assign anything because the system already knows what belongs together 😊

**Comment by asaage** [comment]
It's definetely missing 🤔
Probably an interference with anoher extension..
Do you know a way i could troubleshoot that efficently or am i supposed to composer uninstall/reinstall every suspect one-by-one?

**Comment by asaage** [comment]
@aschempp 
Found the culprit:
https://github.com/terminal42/contao-changelanguage/blob/main/src/EventListener/DataContainer/MissingLanguageIconListener.php#L92

The warning-label only gets applied if the article has "showTeaser" which is something i rarely use.
I have simple, complete articles on my page which are in the same column.
That results in a list of candidates when i try to use the BE switchLanguage widget because i can't see which  ones i have already assigned to a fallback beforehand.
Would you consider reopening this and change the behaviour?
