### ISSUE TITLE
Seitentitel der Originalsprache anzeigen

### ISSUE THREAD

**Issue by gutschik** [terminal42/contao-changelanguage#209]
Wir haben bei einem Kunden den Fall, dass nun Chinesisch und Japanisch als neue Sprachen hinzugekommen sind. Nun ist leider das Problem, dass niemand aus unserem Team mehr die Seiten im Backend identifizieren kann. 

Daher haben wir ganz einfach die Class `MissingLanguageIconListener` etwas erweitert, so dass statt des Icons bzw. in dem Fall dass eine Originalsprache vorhanden ist, der Seitentitel der Originalsprache angezeigt wird:

```
    public function onPageLabel(array $args, $previousResult = null) {
        list($row, $label) = $args;

        if ($previousResult) {
            $label = $previousResult;
        }

        if ('root' === $row['type'] || 'folder' === $row['type'] || 'page' !== \Input::get('do')) {
            return $label;
        }

        $page = PageModel::findWithDetails($row['id']);
        $root = PageModel::findByPk($page->rootId);

        if (!$root->fallback || $root->languageRoot > 0) {
            if ($page->languageMain) {
                $pageMain = PageModel::findByPk($page->languageMain);
                if ($pageMain === null) {
                    return $this->generateLabelWithWarning($label);
                } else {
                    return $this->generateLabelWithMainLabel($label, $pageMain->title);
                }
            } else {

                return $this->generateLabelWithWarning($label);
            }
        }

        return $label;
    }

    private function generateLabelWithMainLabel($label, $mainLabel) {
        return $label . sprintf(
            '<span style="color:#999;padding-left:3px">(%s)</span>',
            $mainLabel
        );
    }
```

Das sieht dann folgendermaßen aus:

![Screenshot 2021-12-09 at 11 35 46](https://user-images.githubusercontent.com/29476/145380966-aafe9ba5-5a7f-41c9-b3f6-011e2c2747f6.png)

Meine Frage wäre nun, ob es denkbar wäre, dass dieser Change auch für andere Kunden interessant wäre? Wenn ja, dann würde ich dazu einen PR anlegen. 

Beste Grüße
Ben

**Comment by fritzmg** [comment]
I would not want to have this by default, but it could be a configurable option 👍

**Comment by aschempp** [comment]
du kannst diesen Titel doch einfach in den Namen der Seite schreiben? Der Titel wird nach meinem Wissen nur im Breadcrumb ausgegeben, und dort kannst du ihn über den Seitentitel überschreiben.

**Comment by fritzmg** [comment]
The title is still used for meta data in the breadcrumb - and would not be correct then.

**Comment by aschempp** [comment]
Ich habe die Funktion spontan in der Version 3.3 eingebaut. Es kann nun im Benutzerprofil gewählt werden, für welche Root-Seiten die Fallback-Titel angezeigt werden sollen 😎
