### ISSUE TITLE
Assigning main language for pages dont work

### ISSUE THREAD

**Issue by taleteller** [terminal42/contao-changelanguage#214]
I had this issue several months ago but the project got postponed, thus its there for a while now.

When editing a pages settings to assign the main languages page, i can click the button to open the selection:
![grafik](https://user-images.githubusercontent.com/1484333/203940253-1e01777b-0436-4f6b-a1c5-3167bb16768e.png)

Opening it causes the first error javascript error in this screenshot. Selecting the desired page and closing the dialog causes the second:
![grafik](https://user-images.githubusercontent.com/1484333/203939869-3d6d05ca-fb2f-4909-8d32-4f7ec4765001.png)

After the dialog is gone, the button for choosing a fallback language vanishes. Saving the pages settings of course does not set any fallback language page at all. 
![grafik](https://user-images.githubusercontent.com/1484333/203940449-640e9974-a9c4-43b3-b6a7-a55acd106a6d.png)
The javascript errors might not be the cause because the pop up in every select file dialog (like pictures), however typically they dont remove the button to choose with and save the selected value.

This happens with Firefox and Chrome in several versions. Contao just got updated to 4.9.36 (did not help), changelanguage is version 3.3.6.

**Comment by fritzmg** [comment]
This is an error within Contao itself: https://github.com/contao/contao/issues/5508

**Comment by taleteller** [comment]
Probably this Issue got closed premature? The issue within Contao got closed a few days ago, this is version 4.9.37 and the Error when choosing a language looks like this now:
![grafik](https://user-images.githubusercontent.com/1484333/205988604-d66240a6-b7cf-4013-82ff-429827b3288e.png)

Line 273 contains ```$("ctrl_languageMain").dispatchEvent(evt);```

**Comment by aschempp** [comment]
`$("ctrl_languageMain").dispatchEvent(evt);` is done by Contao widgets not this extension, I think this would still be a Contao bug if it persists. But please make sure to update to the latest Contao version and clear all your server and browser caches.
