### ISSUE TITLE
Anzeige der Referenzen im Backend, wenn Seite in der Zielsprache 'unveröffentlicht' ist

### ISSUE THREAD

**Issue by 463** [terminal42/contao-changelanguage#221]
Ist es möglich, im Backend die eigene Sprache sowie die Zielreferenzen der anderen Sprachen einzublenden, auch wenn diese in der Seitenstruktur der Zielsprache 'unveröffentlicht' ("ausgeblendet") sind?

Hintergrund: Nutzt man Bereiche des Seitenbaums als "Ressource"/"Container" für Artikel, die anderweitig z. B. in Frontendmodulen oder mehrfach Verwendung finden, sind diese im Seitenbaum gewöhnlich auf 'unveröffentlicht' gestellt. Die Artikel selbst jedoch stehen auf 'veröffentlicht', da sie eben irgendwo anders verwendet werden.<br>Die Cross-Referenzen bei der Artikelbearbeitung sind dann leider nicht sichtbar, obwohl der Wechsel gleichartig wie bei veröffentlichten Seiten sehr angenehm wäre, da die Schwesterartikel ja trotzdem existieren und eben auch bearbeitet werden wollen. Auch die eigene Sprache ist aktuell nur ggf. über die Vorschau der Content-Elemente identifizierbar.

Ggf. könnten auch diese Artikel in einer anderen Farbe dargestellt werden, um anzuzeigen, dass diese in der anderen Sprache noch unveröffentlicht sind (unveröffentlicht im Seitenbaum z. B. orange und als unveröffentlichter Artikel z. B. rot).

**Comment by aschempp** [comment]
mit der Cross-Referenz meinst du das Dropdown welches oben links erscheint? Also die Sprunglinks?

**Comment by aschempp** [comment]
sollte mit 49ee37c1410d429aaf4d814fd08fd58b61a96f1f behoben sein
