### ISSUE TITLE
Keine richtige URL bei Interner Weiterleitung

### ISSUE THREAD

**Issue by jankout** [terminal42/contao-changelanguage#223]
Hallo, 

wenn ich bei einer Seite eine interne Weiterleitung einrichte, wird der Link nicht übernommen und statt dessen wird einfach der ursprüngliche Alias der Seite genommen - hier ist das Bildschirmfoto von den Einstellungen bei der betroffenen Seite

<img width="1213" alt="screenshot 2023-02-01 v 17 59 25" src="https://user-images.githubusercontent.com/3715050/216110764-7caf1192-4210-4bfc-8731-e6386d294f0e.png">

Hier das, was man als Link in Frontend (Statusleiste unten links) sehen kann. 
<img width="1516" alt="screenshot 2023-02-01 v 18 03 18" src="https://user-images.githubusercontent.com/3715050/216111416-7b2e6154-e529-49ba-b8d9-4c35a2a369ce.png">

Siehe https://www.allesbrille-berlin.com/de/aktionen

Gibt es da noch etwas, was ich beachten muss?

**Comment by aschempp** [comment]
das ist leider "Standard" in Contao. Wir arbeiten dort daran das Routing zu verbessern, aber bisher kann Contao das noch nicht. Die Navigation hat hier eine Sonderbehandlung, aber diese haben wir in ChangeLanguage nicht nachgebaut.

**Comment by aschempp** [comment]
This feature has been added in Contao 5.3, implemented in 1efdc6fbefd9e9cb1cbcfe00fefdf883ca0c1a1e
