### ISSUE TITLE
Contao 5.1 - Nachrichtenweiterleitung funktioniert nicht mehr

### ISSUE THREAD

**Issue by heimseiten** [terminal42/contao-changelanguage#225]
Wenn man sich im Frontend in einem Nachrichtenbeitrag befindet (Modul Nachrichtenleser) und dann die Sprache wechselt, wird in die URL ein "/items" geschrieben:

domain.tld/news/testnachricht-de
Leitet zu:
domain.tld/en/news/items/testnachricht-en
Richtig wäre:
domain.tld/en/news/testnachricht-en

Andersrum genauso:
domain.tld/en/news/testnachricht-en
Leitet zu:
domain.tld/news/items/testnachricht-de

Zudem kommt eine Fehlermeldung, wenn man im Backend ein Nachrichtenarchiv bearbeiten möchte:
`Internal Server Error
Was ist das Problem?
An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens`

Leider habe ich es nicht geschafft den Fehler selber zu beheben. Wenn in der Datei NewsNavigationListener.php in Zeile 23 das items entfernt wird, steht zwar das items nicht mehr in der URL, aber der zweite / noch.

**Comment by leofeyer** [comment]
Das Problem mit dem `/items` entsteht vermutlich hier:

https://github.com/terminal42/contao-changelanguage/blob/0efaca90dbeba7013deb184be1af4899d715cd39/src/EventListener/Navigation/AbstractNavigationListener.php#L109-L116

In Contao 5 gibt es kein `TL_AUTO_ITEM` mehr.

**Comment by aschempp** [comment]
There's a `!isset($GLOBALS['TL_CONFIG']['useAutoItem'])` check a line above, so that should already be the case …

**Comment by aschempp** [comment]
Can you check if b2ddbf9c38244d5a4de6d7663266557e3dda52e4 fixes the issue?

**Comment by heimseiten** [comment]
Thank you. But unfortunately this does not fix the issue:

domain.tld/en/news/testnachricht-en
Changes to:
domain.tld/news//testnachricht-de

**Comment by leofeyer** [comment]
I think #228 is the correct fix.

**Comment by heimseiten** [comment]
Yes it is. Thank you!

**Comment by heimseiten** [comment]
But there is still the problem, that the archive can not be opened in the backend.

**Comment by fritzmg** [comment]
> But there is still the problem, that the archive can not be opened in the backend.

See https://github.com/terminal42/contao-changelanguage/pull/226

**Comment by heimseiten** [comment]
Now everything works.
