### ISSUE TITLE
Translation error ("Hauptachiv")

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#232]
There is a typo in the German translation:

![image](https://github.com/terminal42/contao-changelanguage/assets/4970961/3c9d917b-ded6-4da2-8b39-849dc279b590)

It should be "Haupta**r**chiv" instead of "Hauptachiv".

**Comment by aschempp** [comment]
Fixed in 94623320d9c6875ee795c83db436f55104a6acf3
