### ISSUE TITLE
Custom language texts not showing

### ISSUE THREAD

**Issue by tsarma** [terminal42/contao-changelanguage#233]
`"terminal42/contao-changelanguage": "^3.5"`

Custom language texts not showing!

![Screenshot 2023-06-23 at 11 45 31](https://github.com/terminal42/contao-changelanguage/assets/683894/7c7afe73-eb1f-48a3-9ade-a196654aa66e)

**Comment by tsarma** [comment]
The keys used in the above language code like `de-CH`, `fr-CH` etc. are not more working!
When I use the language keys like `de_ch`, `fr_ch` etc. it works.  But, in the root page settings, I've `ISO-639 standard` like `de-CH`, `fr-CH` etc.

**Comment by fritzmg** [comment]
> But, in the root page settings, I've `ISO-639 standard` like `de-CH`, `fr-CH` etc.

Contao normalises that to `de_CH`, etc. You will need to use `de_CH`, not `de-CH`.

**Comment by tsarma** [comment]
Thank you, now I knew. it was different in `Contao 4.9` and now in `Contao 4.13` it is as you've pointed out.

**Comment by tsarma** [comment]
I just updated to the latest version `3.5.8`, and it does not work as intended. 

It can be seen here in the screen shot from Backend and Frontend the order is not the same.
![Screenshot 2023-07-11 at 14 34 12](https://github.com/terminal42/contao-changelanguage/assets/683894/7c865d3c-0bc9-4ceb-8bc4-3bffcce26d67)

**Comment by aschempp** [comment]
noone said it was fixed in `3.5.8`? 😅
