### ISSUE TITLE
Change Language icon too big

### ISSUE THREAD

**Issue by filex99** [terminal42/contao-changelanguage#238]
Hi terminal42, 

within my installation the icon in the change language header is very big: 
![image](https://github.com/terminal42/contao-changelanguage/assets/4587246/915cf80d-2bc6-4a05-a363-9ddcd0f90130)

I already updated to the newest versions: 
Contao Version: 4.13.25
Sprachenwechsler Version: 3.5.8

Thanks for your support!
Felix

**Comment by aschempp** [comment]
looks like the CSS file is not loaded, did you change any of the back end templates? Any error message in your browser console?

**Comment by aschempp** [comment]
does the mentioned css file exist on your server? Maybe the files were not correctly installed.

**Comment by filex99** [comment]
Hi, the file does not exist. Its referenced here:
![image](https://github.com/terminal42/contao-changelanguage/assets/4587246/1bb3c9bf-f971-43d8-a3a8-cad2b963b72c)

There is no folder "bundles" in the root directory. 
![image](https://github.com/terminal42/contao-changelanguage/assets/4587246/c9ae729e-0b97-4e9a-930d-a9b466a54a43)

Should there be such a folder or ist the link to the stylesheet wrong?

**Comment by fritzmg** [comment]
The link is not wrong. You are looking in the wrong place - the `bundles` folder is in your public directory. Also something is awry in your Contao setup in general. You both have a `public` and `web` folder. You will need to sort that out and then run `composer install` again.

**Comment by filex99** [comment]
Thank you for the advice. the missing files/scc were aqll located in the web folder. Even after running composer install. 
I now deleted the folder web and run the composer install again - that moved the missing files to the public folder. 
Thank you for your help, i appriciate it alot. 
The issue is solved now.

**Comment by filex99** [comment]
Thank you!
