### ISSUE TITLE
Alternative für die Seitenverknüpfung

### ISSUE THREAD

**Issue by andreasisaak** [terminal42/contao-changelanguage#24]
Wir haben mit der CCA (Oli vorrangig) eine neue Bibliothek geschrieben mit der wir Kreuzverbindungen in den Seiten schaffen:

https://github.com/contao-community-alliance/language-relations

Diese Language Relations nutzen wir z.B. im Backend Language Switcher (https://github.com/menatwork-ia/backend-language-switcher). Die Implementierung bietet einfach den riesen Vorteil das man aufeinmal die Verbindung zwischen allen Seiten schaffen kann und alle anderen Seiten diese Verbindung dann auch erhalten. Es fällt die Fallback Seite weg, da es in vielen Installationen keinen Startpunkt gibt der alle Seiten enthält und alle anderen richten sich nach ihm. Insgesamt wird dadurch die Pflege deutlich vereinfacht.

Daher meine Bitte, gerne auch Hilferuf an euch: Könntet ihr euch darauf einlassen das wir diese Extension als Alternative in Changelanguage anbieten? Ihr könnt ja eure bisherige Variante drin lassen aber es wäre ja schön das Changelanguage automatisch auf die neuen Verbindungen umsteigt sobald Language Relations installiert ist.

Und in der composer.json setzt man die Ext nicht als Abhängigkeit sondern als Empfehlung. Dann profitieren alle Seiten.

**Comment by xantippe** [comment]
wird die Entwicklung weiter geführt oder ist das Projekt "tot"?

**Comment by frontendschlampe** [comment]
Ist definitiv nicht tot siehe https://github.com/terminal42/contao-changelanguage/issues/58

**Comment by xantippe** [comment]
sorry für meine ungenaue Ausdrucksweise - mit "Projekt" meinte ich "language-relations"

**Comment by frontendschlampe** [comment]
auch das ist nicht tot - siehe https://github.com/terminal42/contao-changelanguage/issues/58

**Comment by aschempp** [comment]
Das kann ich dir nicht beantworten da ich nicht mit der develop-Version arbeite.

**Comment by xantippe** [comment]
@frontendschlampe: soweit verstanden, dass das Projekt auf die todo gekommen ist - wobei ich nicht so recht weiß, was ich von einem Tool halten soll, bei dem es schon ein einem "Zweizeiler" für eine "readme" fehlt... ;-)

**Comment by frontendschlampe** [comment]
Was willst du mir genau damit sagen? Dass das Projekt bescheiden ist, weil es keine Readme gibt? Was soll denn in der Readme stehen? Das Projekt ist damals aus einer schnellen Idee heraus entstanden und wird von uns und ein paar anderen bereits seit Monaten genutzt? Seitdem hat uns leider die Zeit gefehlt, an language-relations weiter zu arbeiten. Auch für eine Readme war einfach keine Zeit vorhanden. Fakt ist, dass wir auf jeden Fall bis Ende des Jahres endlich zu Potte kommen wollen, damit auch die nächste Version von changelanguage endlich veröffentlicht werden kann.

**Comment by amenk** [comment]
:+1:
