### ISSUE TITLE
Kindelemente in Fremdsprachen-Archiv werden nicht angezeigt

### ISSUE THREAD

**Issue by fr4nk2342** [terminal42/contao-changelanguage#249]
Contao: 5.3.8
contao-changelanguage: 3.7.1

Was ich gemacht habe:
- ich habe ein Newsarchiv "de - News"
- ich lege ein neues Newsarchiv "en - News" an
- ich konfiguriere "de - News" als Hauptarchiv 
- in "en - News" verweise ich auf "de - News" als Hauptarchiv

Problem:
- die Kindelemente in "de - News" werden angezeigt
- die Kindelemente in "en - News" können nur geöffnet werden, solange es kein Kindelement gibt. Sobald es eins gibt, bekomme ich folgende Fehlermeldung:

`
Internal Server Error
Was ist das Problem?
Terminal42\ChangeLanguage\EventListener\DataContainer\MissingLanguageIconListener::getChildTranslation(): Return value must be of type ?int, string returned`

**Comment by fritzmg** [comment]
https://github.com/terminal42/contao-changelanguage/issues/245#issuecomment-2126454165

**Comment by aschempp** [comment]
Fixed in c7624ff1341873540252962740244e2541cfb2d7
