### ISSUE TITLE
Weiterleitungsseite im Kontakformular sprachsensitiv

### ISSUE THREAD

**Issue by jpkalus** [terminal42/contao-changelanguage#256]
Wenn ich ein Kontaktformular in mehreren Sprachen einsetzen möchte, stoße ich an das Problem, dass die Weiterleitungsseite immer für eine Sprache festgelegt wird. Schön wäre es, wenn die korrekte Sprachversion der Weiterleitungsseite ausgespielt würde.

Gleiches gilt auf für Module wie Login, Password vergessen/Ändern, Benutzerdaten anpassen und Registrieren.

Auch die Weiterleitungsseite der Mitgliedergruppen könnte davon profitieren.

**Comment by fritzmg** [comment]
Üblicherweise brauchst du immer ein Formular pro Sprache. Du musst ja auch alle sonstigen Texte übersetzen können.

Unabhängig davon: könnte man evt. in der https://extensions.contao.org/?q=language%20aut&pages=1&p=inspiredminds%2Fcontao-language-autoswitch implementieren.

**Comment by jpkalus** [comment]
Danke für deine Reaktion!

Im Formular lassen sich Sprachweichen über inserttags angenehm bauen. Und bei den anderen Modulen bleibt das Argument ja dennoch.

Einen erzwungenen Wechseln möchte ich auf keinen Fall, weshalb das genannte Bundle keine Lösung ist.

**Comment by fritzmg** [comment]
> Einen erzwungenen Wechseln möchte ich auf keinen Fall, weshalb das genannte Bundle keine Lösung ist.

Was genau meinst du damit?

**Comment by jpkalus** [comment]
Ich nehm alles zurück! Das Ding macht genau, was ich wollte! Großartig, danke!

**Comment by fritzmg** [comment]
Für Formulare aber nicht - daher mein Kommentar, dass man das noch implementieren könnte dort.
