### ISSUE TITLE
Hauptarchive nicht auswählbar in Newsarchiv

### ISSUE THREAD

**Issue by mike-tuxedo** [terminal42/contao-changelanguage#257]
Hallo,
ich setze bei https://alureport.com/ euer Plugin ein. Diese Seite zeigt Ausgaben (Newsarchive) und diverse Artikel einer Ausgabe (News eines Newsarchives). Ich habe also diverse Newsarchive mit News und verwende euer Plugin um diese alle zu übersetzen.

Ich habe es irgendwie geschafft einmal ein englisches Archiv einem deutschen Archiv zuzuweisen, leider funktioniert das kein weiteres mal. Meine Intention war das ich alle deutschen Archive als "Hauptarchiv" markiere und dann bei den englischen Archiven das entsprechende deutsche Archiv als "Hauptarchiv" auswähle.

Hab ich da was falsch verstanden was die Funktionsweise betrifft, oder wisst ihr evtl von einem Bug warum das nicht funktioniert?

Ich verwende:
Contao 4.13.47
Euer Plugin (Sprachenwechsler): 3.7.6

**Comment by mike-tuxedo** [comment]
Hallo,
ich konnte das Problem jetzt lösen. Ja ich weiß, nur 15min nach dem Issue sieht es aus als hätte ich mich davor nicht damit beschäftigt, aber ich saß hier wirklich schon Stunden drann und jetzt nach dem Issue stoße ich auf einmal auf die Lösung.

Also falls das noch wem trifft, es müssen im Seitenbaum die Artikelleser Seiten eingeblendet sein, die in den jeweiligen Archiven als Weiterleitung eingestellt sind, damit die "Hauptarchiv" Zuweisung in den Newsarchiven funktioniert.

**Comment by fritzmg** [comment]
> Also falls das noch wem trifft, es müssen im Seitenbaum die Artikelleser Seiten eingeblendet sein, die in den jeweiligen Archiven als Weiterleitung eingestellt sind, damit die "Hauptarchiv" Zuweisung in den Newsarchiven funktioniert.

You mean they were unpublished?

**Comment by mike-tuxedo** [comment]
Yes, if the newsreader-page (that is selected as the redirect page in a newsarchiv) is unpublished, the newsarchiv with that redirectpage set, does not show up as option in the "Hauptarchiv" dropdown.

**Comment by fritzmg** [comment]
I see, I think that could be improved. The published state should be disregarded for this.

**Comment by aschempp** [comment]
Fixed in 78ae2b0790a7d4950de918311ad8caff0b2b09a0
