### ISSUE TITLE
"Hilfe" gegen doppelte Zuweisung

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-changelanguage#29]
Hi,

aktuell ist es möglich, in meinem Seitenbaum der "Nicht-Fallback-Sprache" mehrere Seiten einer Fallbacksprache zuzuordnen... bei sehr großen Seitenbäumen hat man sich in dem Pull-Down der Fallback-Seiten schnell verklickt.

Könnte man dem User hier nicht etwas mehr Hilfe geben z.B.

* schon vergebene Seiten werden im Pull-Down anders farbig ausgewiesen (rot vs. grün oder schwarz vs. grau)
* schon vergebene Seiten lassen sich per Filter-Checkbox ausblenden

Da die Sachen gut per CSS einstellbar sind, müssten die Einträge "nur" eine entsprechende CSS-Klasse erhalten.

**Comment by aschempp** [comment]
In ChangeLanguage v3 verwenden wir nun den Seitenpicker, daher lässt sich das nicht einfach stylen. Bei doppelter Zuweisung erscheint aber ein Fehler wenn die Seite gespeichert wird.
