### ISSUE TITLE
newslanguage und eventlanguage zusammenfügen

### ISSUE THREAD

**Issue by jenda77** [terminal42/contao-changelanguage#31]
Hallo, 

ich fände super, wenn man changelanguage generell auch für News und Events einsetzen könnte, statt einzeln für die jeweiligen Module die entsprechende Erweiterung zu installieren. Andreas wies mich schon auf https://github.com/terminal42/contao.../release/3.0.0 hin, aber das funktioniert leider mit der 3.3.3-Version nicht. Deswegen möchte ich es hier noch einmal als Idee anstoßen. :-) 

Liebe Grüße,

Jan

**Comment by aschempp** [comment]
Implemented in 1847ff72ee2db073018ac217b5ba67cc056f652d

**Comment by jenda77** [comment]
Thank you very much.
