### ISSUE TITLE
Auswahl "Fallback-Seite" leer (contao 3.4.0, changelanguage 2.2.7)

### ISSUE THREAD

**Issue by pgerundt** [terminal42/contao-changelanguage#43]
Hallo zusammen,

contao zeigt nach dem Update nur noch eine leere Selectbox "Fallback-Seite" an; die Informationen sind jedoch noch in der Datenbank vorhanden, es ist nur keine neue Auswahl möglich.

Der Fehler liegt möglicherweise in der Methode findMainLanguageRootForPage() der ChangeLanguage.php

Scheinbar liefert getPageDetails() im Fehlerfall nur NULL zurück, die Property "numRows" ist nicht gesetzt (NULL).

Daher sollte Zeile 116 statt
return $objRoot->numRows ? $objRoot->row() : false;
eher
return is_null($objRoot) ? false : $objRoot->row();
lauten - zumindest ist dann die Selectbox wieder gefüllt.

Hope that helps...

Grüße,
Pascal

Nachtrag: Bug besteht seit 2.2.5, dort wurde
$objRoot = $this->Database->prepare("SELECT * FROM tl_page WHERE id=?")->execute($arrRoot['languageRoot']);
in
$objRoot = $this->getPageDetails($arrRoot['languageRoot']);
geändert, seitdem gibts kein $objRoot->numRows mehr...

**Comment by florianniebuhr** [comment]
Danke für den Hotfix!
Bei mir war das gleiche Problem unter 3.2.14 mit Composer und changelanguage 2.2.7

Spracheinstellung ccTLD
also ohne Flags in der URL und mit .de und .com Domains im Seitenbaum

Hat sofort geholfen, das Problem mit meinem Inserttag {{env::referer}} AUCH behoben, das hatte nicht mehr die zuletzt besuchte Seite aufgerufen. Nach deer Anpassung gings. 

Wobei ich nicht weiß wo da der Zusammenhang besteht?

**Comment by tuxenberger** [comment]
Danke auch von hier für den Hotfix,
hat mir bei Contao 3.2.17 und CL 2.2.7 sehr geholfen.

**Comment by aschempp** [comment]
Habt ihr noch andere Erweiterungen installiert? Ich kann das Problem nicht nachvollziehen.

**Comment by aschempp** [comment]
Behoben in c22cf48e72557b7aec602c92c2b3260fe04ee351
