### ISSUE TITLE
get param should check if it is an array

### ISSUE THREAD

**Issue by Zeromax** [terminal42/contao-changelanguage#45]
in this line https://github.com/terminal42/contao-changelanguage/blob/899a7764479da4036e94de6d5282309d2354ff26/ModuleChangeLanguage.php#L226 the check if the param is an Array is missing.

Otherwise the URL is not build correctly.

Proposal:
```php
foreach( $arrParams['get'] as $k => $v )
{
    if (!is_array($v))
    {
        $arrRequest[] = $k . '=' . $v;
    }
    else
    {
        foreach ($v as $vv)
        {
            $arrRequest[] = $k . '[]=' . $vv;
        }
    }
}
```

**Comment by aschempp** [comment]
Obsolete with the new UrlParameterBag
