### ISSUE TITLE
Wrong link to second language after page copy

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-changelanguage#46]
Nach dem Kopieren einer Seite aus einem Sprachbaum in den Fallback-Baum funktioniert die Verlinkung aus dem Falback-Tree in einen anderen Sprachbaum nicht.

Das liegt daran, dass die kopierte Seite bereits eine Fallbackseite zugewiesen bekam, welche dann auch in der DB steht. In dem Fallback-Baum hat man aber dieses Feld für die Zuweisung nicht, so dass ich die Zuweisung dort wieder entfernen könnte.

Ich konnte die Zuweisung jetzt ohne DB-Zugriff wieder entfernen, indem ich diese eine Setie über "mehrere bearbeiten" bearbeitet habe. Dort sieht man dann das Feld für die Zuweisung und kann sie wieder aufheben. Danach funktioniert wieder alles.

Könntest du den Code bitte so verändern, dass beim Setzen der Verlinkung die Fallbackzuweisung dann ignoriert wird, wenn die Seite in dem Fallbackbaum liegt?

**Comment by aschempp** [comment]
In ChangeLanguage v3 wird die Zuweisung beim kopieren entsprechend entfernt.

**Comment by Aybee** [comment]
Ich danke dir.

**Comment by Samson1964** [comment]
In Contao 3.5.17 ist das immer noch so. Verschiebe ich die Hauptsprachenseite(n), verliert/en die anderssprachige(n) Seite(n) ihre Zuordnung. Muß ich auf Contao 3.5.24 updaten. Gibt es das aktuelle changelanguage überhaupt im ER?

**Comment by Aybee** [comment]
Wirklich? Die Zuweisung auf die Hauptsprachenseite erfolgt doch über eine Seiten-ID und wenn du eine Hauptsprachen-Seite verschiebst, ändert sich doch nicht deren ID!?

**Comment by Samson1964** [comment]
Contao 3.5.17 und changelanguage 3.1.0. Nach dem Verschieben eines englischen Seitenzweiges (Hauptsprache) war im verknüpften deutschen Zweig die Verknüpfung weg. Ich habe die rund 60 Verknüpfungen neu angelegt. Die Artikel waren bis auf einen alle in Ordnung.

Danach habe ich 3.1.1 über das ER installiert, wo das behoben sein soll. Diese Version unterstützt aber keine News, Events und FAQs mehr. Also zurück zu 3.1.0.

**Comment by Aybee** [comment]
>Danach habe ich 3.1.1 über das ER installiert, wo das behoben sein soll. Diese Version unterstützt aber keine News, Events und FAQs mehr. Also zurück zu 3.1.0.

Wo ist denn das dokumentiert, dass keine News... mehr unterstützt werden? Hier kann ich dazu nichts finden https://github.com/terminal42/contao-changelanguage/releases

**Comment by Samson1964** [comment]
#103
