### ISSUE TITLE
Missing label for customLanguageText

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#47]
The field `customLanguageText` of `tl_module` is missing its label in the translations, e.g.: [terminal42/contao-changelanguage/languages/de/tl_module.php#L38](https://github.com/terminal42/contao-changelanguage/blob/master/languages/de/tl_module.php#L38)
```php
$GLOBALS['TL_LANG']['tl_module']['customLanguageText']	= array(' ', 'Bitte geben Sie einen Ersatz für jede Sprache ein.');
```
This causes the checkbox label to be empty when editing the rights of users or groups: contao/core#7858

**Comment by aschempp** [comment]
This was actually intentional because the checkbox before already describes it, but we probably should still fix it.

**Comment by fritzmg** [comment]
Ah I see. Maybe it's possible to check in the language file, whether we are in the rights editing view or something?

**Comment by aschempp** [comment]
@qzminski can you verify the polish labels in https://github.com/terminal42/contao-changelanguage/commit/1b044eec33a31ce0d4b95e8e7fee4d1ce994fb3e ?

**Comment by qzminski** [comment]
Looks good.
