### ISSUE TITLE
resetFallback when copying to the fallback tree

### ISSUE THREAD

**Issue by amenk** [terminal42/contao-changelanguage#50]
Page structure:

DE --> Irgendwas
     --> Nochwas
EN  (Fallbacksprache) --> Something

If I copy now "Nochwas" to EN the languageRoot is not reset to 0. This is causing strange effects.

In https://github.com/terminal42/contao-changelanguage/blob/master/dca/tl_page.php#L119 there is already code for resetting, but I am not sure which cases are handled there.

I think we should add the condition:
if $objPage is in the fallback tree then languageRoot should always be set to 0.

Am I correct?

**Comment by amenk** [comment]
*bump*

**Comment by aschempp** [comment]
The existing code will reset the IDs if you set your root page as fallback. So in your case it would solve the problem by checking and unchecking the fallback checkbox in english. However, I agree we should reset the setting when copying to the fallback language.

**Comment by amenk** [comment]
How is the time plan / roadmap for 3.0.0 ?

**Comment by amenk** [comment]
Anything new?

**Comment by aschempp** [comment]
This is implemented in ChangeLanguage v3 (currently RC).
