### ISSUE TITLE
feature: language switch for multiple domains

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#54]
Currently changelanguage only allows language fallbacks/switch for different languages on the _same_ domain. However, it might be useful if changelanguage also allows language fallbacks on _different_ domains, e.g. when the different languages of your website are spread across different domains
```` 
domain.com
domain.de
domain.fr
```

**Comment by aschempp** [comment]
This is already possible, please see the documentation or contact the community forums for questions.

**Comment by fritzmg** [comment]
It does not seem to be possible in changelanguage 2.2.9. Which documentation are you referring to?

**Comment by aschempp** [comment]
I assure you it is. As I said, please refer to the community forums, there's even a special subforum just for changelanguage.

**Comment by fritzmg** [comment]
I know, what's why I am here: https://community.contao.org/de/showthread.php?54731-Verst%E4ndnis-Frage-mehrsprachige-Seite-Vorteil-von-verschiedenen-Startpunkten&p=382572&viewfull=1#post382572 ;)
I'll test again later today, maybe I messed something up in my test.

**Comment by fritzmg** [comment]
Ah, the problem was, that I didn't set a domain for one website root, thus you would also not be able to switch back to that website root naturally.
