### ISSUE TITLE
Refactoring zwecks Realisierung von InsertTag link_url_lang

### ISSUE THREAD

**Issue by amenk** [terminal42/contao-changelanguage#58]
Ich würde gerne einen Insert Tag analog zu `link_url` realisieren mit dem man eine bestimmte Spracheversion einer PageID ansteuern kann.

z.B.

    {{link_url_lang::42:de}}

Fragen:

1. Soll ich das als PullRequest zum Changelanguage Modul machen oder findest du das zu sehr out-of-scope?
2. Vorbeit dazu wäre ein Refactoring der (recht langen) Methode `\ModuleChangelanguage::compile` und Ausgliederung einer entsprechenden Funktion zum Abrufen der Sprachversion - spricht etwas dagegen? Hätte das Chancen gemergt zu werden?

In dem Zuge bitte ich euch auch um Feedback zu https://github.com/terminal42/contao-changelanguage/pull/48 - warum das nicht im master ist. Danke :) !

**Comment by Toflar** [comment]
Am liebsten würde ich an changelanguage gar nichts mehr weiterentwickeln im Moment. Es hängt schon ewig (gefühlt ein Jahr) eine neue Version rum und sie hängt ausschliesslich an einer anderen Extension die eine generelle Lösung für Sprachverknüpfungen innerhalb Contao bieten soll. Also bau dir besser deine eigene Extension, weil dein Code würde wohl nie gemerged werden bis die Situation geklärt wurde. Ob das jemals eintritt, kann ich auch nicht sagen. /cc @frontendschlampe

**Comment by amenk** [comment]
Hm, good to know ... Was ist das für eine andere Extension?

**Comment by Toflar** [comment]
https://github.com/contao-community-alliance/language-relations/issues/4 <-- das wäre das entsprechende Ticket.

**Comment by frontendschlampe** [comment]
Asche auf mein Haupt - es tut mir wirklich sehr Leid, dass es hier bei uns hängt, aber es haben sich bei uns durch verschiedene Projekte in den letzten Monaten einfach keine freien Zeiten ergeben. Mein Ziel ist es aber, bis Ende des Jahres unsere language-relations soweit fertig zu haben! Großes SORRY!

**Comment by Toflar** [comment]
Hängts an der Zeit oder am finanziellen? Dein Bruder soll mal die Diskussion joinen, weiss aber seinen Github-Usernamen nicht :D

**Comment by frontendschlampe** [comment]
Es hängt eher an der Zeit, die @backbone87 gerade nicht hat, weil er z.Zt. (und auch die letzten Monate) 3-4 Sachen gleichzeitig auf der Uhr hat! Finanziell würde ich was sponsern und @davidmaack hatte eigentlich auch noch was in der Hinterhand. Ich hoffe, das ist auch noch so!

**Comment by Toflar** [comment]
Ok, ich will das Thema auch vom Tisch haben, also wenn's daran scheitern sollte tragen wir unseren Teil dazu bei.

**Comment by frontendschlampe** [comment]
Ja, alles gut! Ich habe das Thema mittlerweile ganz oben auf meiner ToDo-Liste und warte nur noch darauf, dass @backbone87 endlich Zeit hat! :-(

**Comment by aschempp** [comment]
@amenk die ID 42 in deinem Beispiel (`{{link_url_lang::42:de}}` ist die ID der Fallback-Sprache? Warum nicht direkt die ID der richtigen Seite verwenden?

**Comment by amenk** [comment]
Ich hab nicht mehr die geringste Ahnung was ich damit _damals_ bezwecken wollte ... das Alter ... *seufz*

**Comment by aschempp** [comment]
Dann schliesse ich das mal :joy:

**Comment by amenk** [comment]
Jetzt weiß ich es wieder. Es ging im Prinzip darum, sowas wie 

    <a href="{{iflng::de}}{{link_url::876}}{{iflng}}{{iflng::en}}{{link_url::887}}{{iflng}}">
        Foo
    </a>

im Template abzukürzen durch ein Insert Tag mit einem Link immer auf die aktuelle Sprache einer Seite.

**Comment by Toflar** [comment]
Indeed ein cooles Feature, könnte ich auch brauchen!

**Comment by aschempp** [comment]
Die InsertTags in ChangeLanguage 3 sind verfügbar als `{{changelanguage_*::*::*}}`. 

Beispiel: `{{changelanguage::3::de}}` erzeugt dasselbe wie `{{link::?}}` wobei die ID der deutschen Seite für ID 3 genommen wird.

Es können alle bekannten `{{link_*}}` insert tags benutzt werden, also z.B. `{{changelanguage_open::*::*}}`.
