### ISSUE TITLE
Anzeige Auswahlfeld "erzwingen"

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-changelanguage#59]
Hi,

aktuell wir das Auswahlfeld für die Zuordnung der Seiten nur angezeigt, wenn bei Domain zwei gleiche Domainnamen - inkl. Subdomain enthalten sind...

Wenn man für die Vorbereitung einer neuen Sprachseite z.B. die Subdomian en.domain.de verwendet, kann man die Seeitenreferenzierung nicht eingeben - dass muss man dann nach Freischaltung machen oder per htaccess-Schutz.

Kann man nicht eine Anzeige "erzwingen"?

Gruss & Dank

**Comment by aschempp** [comment]
Ich denke das wäre der falsche Ansatz. Du solltest die Root-Seite korrekt konfigurieren aber nicht veröffentlichen (und dann ggf. Frontend-Vorschau nutzen).

**Comment by xantippe** [comment]
... o.k. - danke für den Tipp!
