### ISSUE TITLE
Error in php 7.0

### ISSUE THREAD

**Issue by hamidabbaszadeh** [terminal42/contao-changelanguage#60]
There is a problem in php 7.0

Fatal error: Uncaught exception Error with message Function name must be a string thrown in system/modules/changelanguage/ModuleChangeLanguage.php on line 204

#0 system/modules/core/modules/Module.php(282): ModuleChangelanguage->compile()
#1 system/modules/changelanguage/ModuleChangeLanguage.php(72): Contao\Module->generate()
#2 system/modules/core/library/Contao/Controller.php(313): ModuleChangelanguage->generate()
#3 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'header')
#4 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 index.php(20): Contao\FrontendIndex->run()
#6 {main}

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-changelanguage/commit/a972e8851edec5dc754f55f4dc76461261ebea17.

Can you check if the 2.2.10 hotfix branch works for you on PHP7 or if there are more issues? I'd like to wait with publishing it until you approve :) Thanks Hamid!

**Comment by hamidabbaszadeh** [comment]
:+1:  It's work.

**Comment by Toflar** [comment]
Thank you, published then :)
