### ISSUE TITLE
"Replizieren" von Sprachversionen im alternate hreflang Tag

### ISSUE THREAD

**Issue by amenk** [terminal42/contao-changelanguage#61]
Unsere SEO Abteilung hätte gerne alternate hreflang Tags für de-CH und de-AT.

Aktuell habe ich das durch einen "Hack" gelöst:

	--- ModuleChangeLanguage.php	(revision 1008)
	+++ ModuleChangeLanguage.php	(revision 1009)
	@@ -311,6 +311,14 @@
	 
		     if ($blnDirectFallback) {
		         $GLOBALS['TL_HEAD'][] = '<link rel="alternate" hreflang="' . $arrRootPage['language'] . '" lang="' . $arrRootPage['language'] . '" href="' . specialchars($domain . $href) . '" title="' . specialchars($pageTitle, true) . '"' . ($objPage->outputFormat == 'html5' ? '>' : ' />');
	+
	+                if ($arrRootPage['language'] == 'de') {
	+                    foreach(array('de-CH', 'de-AT') as $replicateLang) {
	+                        $GLOBALS['TL_HEAD'][] = '<link rel="alternate" hreflang="' . $replicateLang . '" lang="' . $replicateLang . '" href="' . specialchars($domain . $href) . '" title="' . specialchars($pageTitle, true) . '"' . ($objPage->outputFormat == 'html5' ? '>' : ' />');
	+                    }
	+
	+                }
		     }
	 
		     $c++;

hätte soetwas Chancen auf einen Merge? ggf. würde ich die "replicateLang" noch konfigurierbar machen. Oder ist das zu speziell?

**Comment by aschempp** [comment]
Closing this in favor of #62
