### ISSUE TITLE
Korrektur des hreflang-Tags

### ISSUE THREAD

**Issue by k-webdesign** [terminal42/contao-changelanguage#63]
Hi,

die derzeitige Implementierung des hreflang-Tags ist nicht optimal/falsch. Ich habe mich dazu mit diversen SEO-Kollegen beraten und wir kamen alle zu dem Schluss, dass es so aussehen muss, um ungewünschte Ranking-Effekte zu vermeiden:

Ist:
```
<link rel="alternate" hreflang="de" lang="de" href="de/" title="Contao Open Source CMS“>
```

Soll:
```
<link rel="alternate" hreflang="de" href="https://contao.org/de/">
```

Das bedeutet, dass der title und lang entfernt werden müssen und der href sollte die vollständige URL zeigen.

Viele Grüße,
Kim

**Comment by aschempp** [comment]
Ich glaub hier fehlt dein HTML? :D

**Comment by lucasjahn** [comment]
Dem Kollegen geb ich vollkommen Recht. Im moment sieht es bei mir so aus:

```
<link rel="alternate" hreflang="en" lang="en" href="en/" title="Home">
```

sollte aber so aussehen

```
<link rel=“alternate” hreflang=“en” href=“http://www.yoursite.com/en/” />
```

D.h. title-Attribut, sowie lang-Attribut weg und das href sollte die komplette URL enthalten.

**Comment by k-webdesign** [comment]
Oh Mist, in der Vorschau wurde das angezeigt :D lucasjahn hat Recht, wie es in seinem Code steht muss das eigentlich sein.

**Comment by aschempp** [comment]
Zum Thema der absoluten URL: #32, #38, #39

Bezüglich dem anderen, aus welchem Grund sollte da kein Titel sein? Und das `lang`-Attribut bezieht sich ja dann auf den Titel, was korrekt wäre (weil der Titel wohl in der Sprache des Links ist).

**Comment by k-webdesign** [comment]
Die volle URL erscheint wohl, sobald man eine Base URL einträgt. Damit kann man das individuell anpassen.

Es ist schlicht falsch, wenn man einen title und das lang Attribut einsetzt. Nirgendwo konnte ich eine Doku finden, die das einsetzt. Es gibt nur lauter Best Practice Gegenbeispiele, indem er auf das Notwendige reduziert wird. Und daher sollte er bitte angepasst werden, um Google nicht zu signalisieren, dass man mit diesem Tag nicht umgehen kann. 

https://moz.com/blog/hreflang-behaviour-insights <- hier hat CNN den hreflang mit dem title angereichert und Google kommt darauf überhaupt nicht klar

Anebei 2 Generatoren:
https://www.sistrix.de/hreflang-guide/hreflang-generator/
http://www.aleydasolis.com/en/international-seo-tools/hreflang-tags-generator/

Und etwas Lesestoff:
https://support.google.com/webmasters/answer/189077?hl=de
https://www.sistrix.de/frag-sistrix/onpage-optimierung/wie-nutze-ich-das-x-default-hreflang-link-attribut-richtig/
http://www.121watt.de/seo/hreflang/
