### ISSUE TITLE
hreflang über Template editierbar machen

### ISSUE THREAD

**Issue by k-webdesign** [terminal42/contao-changelanguage#64]
Hi,

wäre es möglich, den hreflang über ein separates Template updatesicher ändern zu können?

Der hreflang ist äußerst mächtig und kann von einem SEO z.B. dazu genutzt werden um eine bestimmte Sprachversion auf die Keywords dieser Sprachversion international ranken zu lassen, beispielsweise die US-Version eines Shops auch in Indien, Bangladesh, usw. 
Das bedeutet also Rankings ohne explizite Sprachversion dieses Shops. 

Im ersten Schritt wäre eine Pflege über ein Template schon extrem angenehm, über ein Modul können wir ggf. in einem 2. Schritt sprechen, falls überhaupt nötig :)

Viele Grüße,
Kim

**Comment by aschempp** [comment]
ich bezweifle dass das Sinn und Zweck von Changelanguage ist?

**Comment by aschempp** [comment]
Erste Version in a416a546cdf9da6021dc6ce14b933908756c3dd4 implementiert.

**Comment by aschempp** [comment]
Erste Version in a416a546cdf9da6021dc6ce14b933908756c3dd4 implementiert.
