### ISSUE TITLE
Sprachwechsel ohne Verweis auf Hauptsprache

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-changelanguage#65]
Hallo,

wäre es möglich dass man bei z. B. 3 Sprachen zwischen den beiden Sprachen wechseln kann die keine Hauptsprache sind ohne dass es eine Fallbackseite in der Hauptsprache gibt?

z. B.:
DE (Hauptsprache), NL, FR

Seite zwischen der gewechselt werden soll existiert nur in den Sprachen NL und FR. Also nicht in dem Fallback DE. 

Gruß

**Comment by aschempp** [comment]
das ist bisher nicht möglich. Eventuell wird das mit der Version 3 kommen, die befindet sich aber seit 2 Jahren oder so in Entwicklung weil wir auf ein Drittmodul warten :-)

**Comment by stefan-at-work** [comment]
wie ist denn hier der Stand der Dinge?

**Comment by aschempp** [comment]
Ich glaube nicht dass sich hier mal etwas ändert 🙈
