### ISSUE TITLE
Hreflangs ohne Rücklinks

### ISSUE THREAD

**Issue by akroii** [terminal42/contao-changelanguage#66]
Hallo,
ich habe von Google eine Email bekommen, dass einige Seiten keine Rücklinks aufweisen.
Ist es möglich das html href-Tag komplett auszuschalten, wenn keine Fallbacksprache gesetzt ist?

Contao 3.4.4
changelanguage 2.2.8   6

**Comment by akroii** [comment]
Im Forum: https://community.contao.org/de/showthread.php?58442-Google-WMT-keine-R%FCcklinks&p=400247&viewfull=1#post400247

**Comment by aschempp** [comment]
@k-webdesign kannst du dazu etwas sagen?

**Comment by k-webdesign** [comment]
Der Foremthread klingt mir ganz danach, als sei da grundsätzlich etwas falsch konfiguriert. hreflang auszuschalten macht keinen Sinn, denn er kann sehr wohl genutzt werden, wenn man nur eine Sprache hat. Das ist sogar sehr sinnvoll, insbesondere wenn man Inhalte nur für den CH, AT oder DE Sprachraum optimieren möchte. Im Beispiel war die Domain eine .com, weshalb er hier sogar wichtig ist.

Kurzum: Ausschalten macht keinen Sinn. Mit einem konkreten Beispiel könnte ich mehr dazu sagen.

**Comment by akroii** [comment]
Mein Beispiel:
Meine Website ist komplett in [DE] + Sprachen-Fallback angelegt. Im deutschen Seitenbaum existiert eine Seite "Historie". Für die englische Übersetzung habe ich einen neuen Seitenbaum angelegt ([EN] ohne Sprachen-Fallback) um die englische Seite "History" anzulegen.
Dort habe ich der Seite "History" die Fallback Sprache der deutschen Hauptseite im deutschen Seitenbaum[DE] zugewiesen.

Folge davon war, dass ich von Google eine Email bekommen habe, dass meine Website Hreflangs ohne Rücklinks aufweist. Logisch, denn der Hreflang-Tag zeigt ja überall auf die selbe Seite, ausser bei History/Historie. Dort hat das Tag ja den englisch-sprachigen Gegenspieler.

So wie ich Google verstanden habe, macht es kein Sinn Hreflangs zu verwenden wenn man keine Sprachalternative zur Verfügung hat. Deswegen möchte ich bei der Option "Keine Sprache" im englischen Seitenbaum, dass der Hreflang-Tag nicht ausgegeben wird. Denn bisher tut er das trotzdem und changelanguage zeigt überall auf die selbe Seite.

Du hast eine PM.

**Comment by aschempp** [comment]
Danke @k-webdesign für's Feedback. Ist es denn sinnvoll nur einen einzelnen Rücklink zu haben, der immer nur auf die aktuelle Seite zeigt? Also angenommen man hat wirklich nur einen Seitenbaum, würde ein `alternate`-Link ja wenig Sinn ergeben?

**Comment by akroii** [comment]
Richtig! Nur einen `alternate` Link anzuzeigen laut Google verkehrt.
Das ist genau das was ich oben versucht habe zu erklären.

**Comment by aschempp** [comment]
Was meint denn meine SEO-Expertin dazu? 😁

**Comment by aschempp** [comment]
Ich schliesse dies mal, bitte ein neues Ticket eröffnen falls das in ChangeLanguage 3 weiterhin zutrifft.
