### ISSUE TITLE
hreflang / auto item

### ISSUE THREAD

**Issue by bcat-eu** [terminal42/contao-changelanguage#67]
Folgendes Problem: Wenn man sich auf einer Detailseite befindet, z.B. bei Events Erweiterung domain.de/event/event-slug.html, wird für die aktive Sprache so etwas in Code erscheinen `href="event.html"`, also ein Link zu "parent" Seite die Details-Modul hat.

Eine mögliche Lösung wäre die aktive URL getrennt zu bestimmen und dabei wenn nötig auch auto Item zu beachten. In ModuleChangeLanguage.php

    if ($blnDirectFallback) {

        $hrefUrl = ($active) ? specialchars($domain . $this->getCurrentUrl()) : specialchars($domain . $href) ;

        $GLOBALS['TL_HEAD'][] = '<link rel="alternate" hreflang="' . $arrRootPage['language'] . '" lang="' . $arrRootPage['language'] . '" href="' . $hrefUrl . '" title="' . specialchars($pageTitle, true) . '"' . ($objPage->outputFormat == 'html5' ? '>' : ' />');
    }

Und dann die Funktion die URL bestimmt beachtet auch auto_item Param:

    /**
     * Determine active url including auto item
     *
     * @return string
     */
    protected function getCurrentUrl() {

        global $objPage;

        $strCurrentUrl = ($GLOBALS['TL_CONFIG']['useAutoItem'] && isset($_GET['auto_item']))
            ? $this->generateFrontendUrl($objPage->row(), '/' . \Input::get('auto_item'))
            : $this->generateFrontendUrl($objPage->row());

        return $strCurrentUrl;
    }

Nach Bedarf kann man diese noch z.B. um query string erweitern.

**Comment by aschempp** [comment]
Dazu gibt es die Option "URL Parameter beibehalten". Oder die Unterstützung für das entsprechende Modul. Ich arbeite aktuell an Version 3 welches die Kalender explizit unterstützen sollte.
