### ISSUE TITLE
Fallback erzeugt Ordner

### ISSUE THREAD

**Issue by Dani79** [terminal42/contao-changelanguage#69]
Hallo,

ich habe jetzt die changelanguage 3.0 ausprobiert, Einstellungen die Sprachen angegeben (de und en). Wenn ich jetzt von DE auf EN Springe (Reader Seite) dann erzeugt er mir einen Ordner, und somit ist die Fallback Seite nicht zu finden, da der Ordner dazwichen gehangen wird. Hier die Seite:

http://www.hotel-christoph.com/de/hotel-ellmau-pauschalangebote-detail/skiwochen-ellmau.html

Dort auf EN oben, dann findet er die Seite nicht. Woran liegt das? Gibts da eine Lösung?

Danke
Dani

**Comment by Toflar** [comment]
Changelanguage 3.0 existiert doch noch gar nicht?

**Comment by Dani79** [comment]
https://github.com/terminal42/contao-changelanguage/tree/release/3.0.0

**Comment by aschempp** [comment]
Da arbeite ich gerade dran, die würde ich noch nicht benutzen 😂

**Comment by Toflar** [comment]
Und wie kommst du darauf, dass das produktiv eingesetzt werden kann, wenn ich fragen darf? :-) Alles was nicht getaggt ist, sollte man ja grundsätzlich nicht einsetzen.

**Comment by Dani79** [comment]
Wurde im Forum genannt, unter Vorbehalt :) Und aus der Not habe ich es einfach getestet. Bei einem Projekt funktioniert das witchen schon, aber wenn du dran arbeitest hat sich sicher wieder etwas geändert.

**Comment by fritzmg** [comment]
Wurde hier von @aschempp vorgeschlagen: https://community.contao.org/de/showthread.php?12636-Events-Language&p=329734&viewfull=1#post329734 ;)

**Comment by aschempp** [comment]
Im Juni 2014 ;-)

**Comment by fritzmg** [comment]
> Im Juni 2014 ;-)

Na dann kann's ja jetzt nur noch besser sein :D

**Comment by aschempp** [comment]
Ich schliesse das mal, bitte erst testen wenn wir eine Beta veröffentlichen.
