### ISSUE TITLE
Changelanguage in kombination mit Newslanguage

### ISSUE THREAD

**Issue by havutcuoglu** [terminal42/contao-changelanguage#70]
Sorry das ich das hier her poste. Ich weiss echt nicht ob das Problem von Changelanguage oder Newslanguage stammt.

**Folgendes ist mir aufgefallen:**
Ich habe unter Contao 3.2.21 festgestellt, wenn ich die Changelanguage 2.2.0 und Newslanguage 2.1.1 Erweiterungen zusammen verwende, damit ich die einzelne Einträge zu den sprachen  zuweisen kann, funktioniert Newslanguage und Changelanguage nicht korrekt.

Obwohl im Backend das mit dem auto-items deaktiviert ist wird fehlerhafte Ausgabe erzeugt.
Wenn ich die Ordner URLs deaktiviere dann funktioniert das ganze wie es sein soll, was aber nicht korrekt ist bei Seiten die schon lange am laufen sind.

MfG

**Ausgabe in Frontend**
3 Seitenstartpunkte, DE, EN, FR.
Hauptsprache EN, aufgerufen wurde News in FR

Korrekte URL: http://www.domain.fr/nouvelles-detail/duesseldorf-131.html
Diese Teil ist zuviel: duesseldorf-122/auto_item/
```
<!-- Ausgabe Head -->
<link rel="alternate" hreflang="de" lang="de" href="http://www.domain.de/aktuelles-detail/duesseldorf/auto_item/duesseldorf.html" title="Aktuelles-Detail">

<link rel="alternate" hreflang="en" lang="en" href="http://www.domain.com/news-detail/duesseldorf-122/auto_item/duesseldorf-122.html" title="News-detail">

<link rel="alternate" hreflang="fr" lang="fr" href="http://www.domain.fr/nouvelles-detail/duesseldorf-131/auto_item/duesseldorf-131.html" title="Nouvelles-détail">

<!-- Ausgabe Sprachwechsler -->
<a href="http://www.domain.de/aktuelles-detail/duesseldorf/auto_item/duesseldorf.html" title="Aktuelles-Detail" class="lang-de first" hreflang="de" lang="de">DE</a>

<a href="http://www.domain.com/news-detail/duesseldorf-122/auto_item/duesseldorf-122.html" title="News-detail" class="lang-en" hreflang="en" lang="en">EN</a>
```

**Comment by aschempp** [comment]
Kann es sein dass sich dies erledigt hat (gemäss Forum)?
Wir arbeiten aktuell an einer neuen Version von ChangeLanguage, bei der Newslanguage bereits integriert ist. Da ich für das alte keine Testumgebung mehr habe, kann ich das leider gerade nicht nachstellen…

**Comment by havutcuoglu** [comment]
Ok. Ich habe jetzt alles mögliche probiert und konnte das Problem nicht beheben.
Da es auf dem Kunden Server war wollte ich nicht alles löschen und neu einspielen aber es blieb mir nicht anderes übrig. Alles runter geschmissen und neu installiert bzw. überschrieben. Und es funktioniert.

Vielen Dank für dein Feedback und über die neue ChangeLanguage-Erweiterung Info.
