### ISSUE TITLE
Hook for Navigation

### ISSUE THREAD

**Issue by may17** [terminal42/contao-changelanguage#75]
Changelanguage generates an navigation template with closed template vars. In some cases it would be great to extend / manipulate those template vars. An hook would be a nice.

**Comment by aschempp** [comment]
Which version do you use?

There already is a regular Contao hook to modify templates?

**Comment by may17** [comment]
I am using Contao 3.5.12  and changelanguage Version 2.2.0

Did you mean the parseFrontendTemplate hook?

**Comment by aschempp** [comment]
I did mean one of those, yes. Maybe you should also check out changelanguage 3 (currently RC)

**Comment by may17** [comment]
The problem is that i need $arrLanguagePages[$arrRootPage['language']] for my purpose to get access to other page fields. I see no other way to get this data without a specific hook in the modul.

**Comment by Toflar** [comment]
This doesn't exist at all anymore in version 3.
