### ISSUE TITLE
customLanguage subpalette doesn't show

### ISSUE THREAD

**Issue by micha-nerdlichter** [terminal42/contao-changelanguage#76]
Somehow the toggle for the customLanguage subpalette seems to be broken: http://i.imgur.com/pCpIUCn.png

I'm using the 3.0.1 hotfix (558f368) on contao 4.2.2.

**Comment by aschempp** [comment]
Looks like you did not install the dependencies (MultiColumnWizard) ?

**Comment by micha-nerdlichter** [comment]
I did, at least composer did. And it symlinked the vendor folder to ```system/modules```. But I missed to add the following line to the bundles-Array in ```AppKernel.php```:
```php
new ContaoModuleBundle('multicolumnwizard', $this->getRootDir()),
```
I find it quite difficult to figure out, which bundle and which dependencies must be added to ```AppKernel```. I hope that in future versions the extentsions will handle this on their own.

But everything works fine now, thank you.
