### ISSUE TITLE
Can't set dependent calendar/news archive, sublevel linking defect

### ISSUE THREAD

**Issue by johannes-bittner** [terminal42/contao-changelanguage#78]
After updating to 3.0.1, ~~second level links to the corresponding language version don't work anymore (links to the upper level)~~. 
Linking only works correctly from main language (DE) to second language (FR), not vice-versa. Language versions have their own domain names.
Also, I can't set a dependent calendar/news archive in the corresponding calendars/archives. Main language pages are all correctly set. Extension re-installed, caches emptied etc.

**Comment by Ma3xl3** [comment]
@johannes-bittner i got the same problem, downgrading to 3.0.0 has the same effect. I´m on contao 3.5.16

**Comment by aschempp** [comment]
can you post a screenshot of what's not working?

**Comment by johannes-bittner** [comment]
**Problem linking from second language to main language when using different domain names:** 
![2016-09-28 2](https://cloud.githubusercontent.com/assets/1597697/18932726/078759d2-85d2-11e6-849f-4940ec7749ca.png)
The main language page is correctly linked to its correspondent french counterpart.

![2016-09-28](https://cloud.githubusercontent.com/assets/1597697/18933070/3e192f06-85d3-11e6-855f-fdb7378d2041.png)
The french page, however, links back to the parent page, although the reference page ("Seite in der Hauptsprache") is correctly set:

![fehler-chlng-seitenstruktur](https://cloud.githubusercontent.com/assets/1597697/18932850/7dd0dc44-85d2-11e6-8f80-c071c13f8471.jpg)
Interesting detail: the page order in the modal box is not displayed correctly, e.g. messed up.

**Unable to set dependant calendars/news archives:**
![2016-09-28 3](https://cloud.githubusercontent.com/assets/1597697/18932989/f5270f5c-85d2-11e6-861a-6eb81166da32.png)
I can't set calendars/news archives as dependent, neither existing ones nor new ones.

**Comment by aschempp** [comment]
Regarding calendar/news linking, please read the manual: https://github.com/terminal42/contao-changelanguage/blob/master/docs/03-advanced.md#configuring-redirect-page
if the problem still exists, create a new issue as each issue should only be about one topic.

Did you upgrade your installation from changelanguage 2.x? Did you check if the parent page is maybe linked to the gallery page as well?

**Comment by aschempp** [comment]
Language switching is fixed in 22d9482df1d1d318e7428eaaec2a3926e8329e07
