### ISSUE TITLE
Sprache wird im Link falsch generiert

### ISSUE THREAD

**Issue by jonas1616** [terminal42/contao-changelanguage#79]
<img width="541" alt="bildschirmfoto 2016-09-22 um 17 27 03" src="https://cloud.githubusercontent.com/assets/10653817/18754690/d83118ea-80e9-11e6-8748-8a98aef5cc26.png">

Ich habe im als Fallbacksprache de. Die Sprache fr wird erkannt jedoch im Link selber ist de als Sprache.

Fallbackseiten im Backend sind angegeben.

Contao 3.5.6
changelanguage 3.0.1

**Comment by aschempp** [comment]
Das ist ein Contao Bug, du musst ein Update auf die neuste Version machen.

**Comment by jonas1616** [comment]
Danke hat geklappt.
