### ISSUE TITLE
Mehrsprachigkeit mit mehreren Domains

### ISSUE THREAD

**Issue by dhe** [terminal42/contao-changelanguage#80]
Problem bei der Sprachumschaltung mit mehreren Domains

Settings:
---
www.domain.de ist für die deutsche Seite
www.domain.com für die englische Seite 

DNS (Rootpages):
---
Seite DE:
- DNS: www.domain.de
- Sprache: de
- Sprachenfallback: ja
- Hauptdomain: "Dies ist die Hauptdomain"

Seite EN:
- DNS: www.domain.com
- Sprache: en
- Sprachenfallback: ja (sonst erscheinen keine Spracheinstellungen in den regulären Seiten)
- Hauptdomain: www.domain.de ist die Hauptdomain.

<img width="948" alt="settings-de" src="https://cloud.githubusercontent.com/assets/130322/18984765/a5bcefea-86f4-11e6-9edc-78b166864e01.png">
<img width="941" alt="settings-en" src="https://cloud.githubusercontent.com/assets/130322/18984766/a5c143f6-86f4-11e6-900a-ecd68ca37b30.png">
<img width="941" alt="settings-module" src="https://cloud.githubusercontent.com/assets/130322/18984835/1b06677c-86f5-11e6-8e04-632b0b07faf7.png">

Sprachwechsler Modul:
Sprachen ohne direkte Hauptsprache ausblenden: false (wenn true, verschwindet der Sprachwechsler nach dem Wechsel von DE -> EN)

Folgendes Verhalten:
Ich kann von jeder Seite von DE nach EN wechseln, umgekehrt aber nicht(!), da werde ich immer auf die Root Seite DE geleitet.

Seite DE www.domain.de/alias-de/alias-de2 wird zu www.domain.com/alias-en/alias-en2 weitergeleitet, **richtig**. 

Seite EN www.domain.com/alias-en/alias-en2 wird zu www.domain.de/[alias-rootpage] weitergeleitet, **falsch**.

System:
---
- Contao 3.5.17
- changelanguage 3.0.1

**Comment by fritzmg** [comment]
I can confirm the problem as well.

**Comment by aschempp** [comment]
Fixed in 22d9482df1d1d318e7428eaaec2a3926e8329e07

**Comment by dhe** [comment]
Thank you. Works fine!
