### ISSUE TITLE
don't switch to root page alias

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-changelanguage#81]
Whenever a page does not have a corresponding page set in the fallback language, the language switcher offers to switch to the respective language's _root page alias_. 

e.g. if `example.org/en` is the fallback and the fallback's website root's alias is `website-en` and you are on `example.org/de/foo.html` and that page does not have a corresponding page set in the fallback language, then the `EN` entry of the language switcher will link to `example.org/en/website-en.html`.

Technically this works, because Contao will still automatically just display the content of the start page of that website root under that url. However, it's not really a pretty solution.

Instead, the language switcher should just link to the start page of that website root, which will generate a link like `example.org/en` (if the start page's alias is `index`) for example. Or the language switcher should just omit the alias part in another way.

**Comment by aschempp** [comment]
Fixed in faecce6e08539747a7fdae2520f21022a783ea79
