### ISSUE TITLE
copy news from a another language all fields are disappeared

### ISSUE THREAD

**Issue by palmi** [terminal42/contao-changelanguage#84]
when i copy a news from german archive  and whant to paste it in the englisch archive all fields expect the the "master article" is not visible
version 3.02 contao 3.5.17

Update: it happens only when External URL is selected 

![changelanguage](https://cloud.githubusercontent.com/assets/1281826/19381396/aafe827c-91fb-11e6-8ec7-2bbde20aad91.png)

**Comment by aschempp** [comment]
I cannot reproduce this issue. Are you sure it's related to ChangeLanguage?

**Comment by palmi** [comment]
Hi, i made a clean install and it works.
i find out that is a problem in combination with contao-legacy/tags.
