### ISSUE TITLE
Warnhinweis bei nicht ausgewähltem Fallback-Artikel deaktivieren

### ISSUE THREAD

**Issue by balduin-kowalski** [terminal42/contao-changelanguage#85]
In der Seitenstruktur wird bei Seiten für die noch keine Fallback-Sprache definiert ist ein kleines Warnschild angezeigt. An dieser Stelle ist das zwar schon sinnvoll, aber leider wird das Icon auch in der Artikelübersicht bei jedem Artikel angezeigt für den noch kein Fallback-Artikel ausgewählt wurde. Das macht meiner Meinung nach aber nur Sinn, wenn man z.B. die Artikelnavigation nutzt. Im „Normalbetrieb“ ist es eher lästig auch noch alle Artikel miteinander verknüpfen zu müssen wenn es nicht unbedingt nötig ist. Wenn man das aber nicht tut, bleiben die Warnschilder sichtbar. Man kann zwar einstellen, dass bestimmte Benutzer den Fallback-Artikel nicht auswählen können, aber das Warnschild sehen die dann trotzdem.

Wäre es also möglich das Warnschild für Artikel einfach auszublenden?

**Comment by aschempp** [comment]
Wie wäre es dass der Hinweis nur erscheint wenn Artikel-Teaser aktiviert sind?

**Comment by Toflar** [comment]
Es sollte ausserdem sowieso nur dann angezeigt werden, wenn mehr als 1 Artikel in der selben Spalte existiert. Sonst ist eine Verlinkung ja nicht zwingend.

**Comment by aschempp** [comment]
> Es sollte ausserdem sowieso nur dann angezeigt werden, wenn mehr als 1 Artikel in der selben Spalte existiert. Sonst ist eine Verlinkung ja nicht zwingend.

Für's Backend nicht, für's Frontend aber schon.

**Comment by Toflar** [comment]
Stimmt, aber nur dann wenn Teaser aktiviert ist, das ist richtig.
