### ISSUE TITLE
More options to keep query parameters

### ISSUE THREAD

**Issue by joergmoldenhauer** [terminal42/contao-changelanguage#86]
It is a very nice feature that you can choose query parameters which should be kept in the link and alternate-tag for each page individually. However I need a little more options in choosing these query paramters.

I am specifically talking about the pagination (of a news archive for example). Since issue contao/core#4141 query parameters for paginations are unique. So I do not have a parameter `page` but instead `page_a21` or something like that.

It would be nice if I could keep all query-parameters which start with `page`. Maybe by typing `page*` in the option textfield.

It would also be nice if I could decide to simply keep all query parameters. Maybe by typing `*` in the option textfield.

**Comment by joergmoldenhauer** [comment]
On second thought my problem with the pagination query parameters might not be solved by simply keeping all parameters. Instead I think there is the need to assign the pagination query parameters of the different languages to each other.

For example on news page 2 I have the paramter ´page_a21=2´ in german and ´page_a72=2´ in english. So there should be a link from ´?page_a21=2´ to ´?page_a72=2´.

**Comment by aschempp** [comment]
First of all, the `page` number of the parameter is unique on each page, so it should be fairly easy to just enter `page_a21` in the page configuration, as you do know what actual pagination number is on that page.

Secondly, I don't think switching the page and keeping the pagination is a good idea. In most cases, the same page will not result in the same content (only if you have the exact same number of items). Also, I can't come up with an easy way to implement this.

I suggest you use the PHP hook to implement this case just for your system. If you can find a generic solution, feel free to create a pull request.

**Comment by fritzmg** [comment]
> First of all, the page number of the parameter is unique on each page, so it should be fairly easy to just enter page_a21 in the page configuration, as you do know what actual pagination number is on that page.

No, that won't work, it's unique to the module: https://github.com/contao/core/blob/3.5.17/system/modules/news/modules/ModuleNewsList.php#L113
And the module (and thus its ID) will probably not be the same.

> Secondly, I don't think switching the page and keeping the pagination is a good idea.

I agree with that though 👍

**Comment by joergmoldenhauer** [comment]
I think you are right with the thought that the keeping the pagination on page switch is not a good idea. I only came up with this issue because our SEO expert suggested that we should keep the query parameters in the alternate tags. But I don't think there will be a great harm in loosing the pagination query parameter.

So thanks for your time anyway.
