### ISSUE TITLE
Is it possible to use another child_record_callback?

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-changelanguage#87]
With this extension installed I can not use my own child_record_callback e.g. with tl_news. Is this a known limitation? Or is there a tutorial showing how to do this?

**Comment by fritzmg** [comment]
It's probably not working because `changelanguage` inserts all its hooks via the `loadDataContainer` hook and thus overriding your hook.

**Comment by Toflar** [comment]
We could try the same here as I did for the label_callback @aschempp? See https://github.com/terminal42/contao-changelanguage/commit/883b253cb7cb2e2fc67251a947570fcfb482ee68.

**Comment by aschempp** [comment]
Yeah we could do that I guess 👍

**Comment by aschempp** [comment]
I have implemented a generic solution in 9cd34d5
