### ISSUE TITLE
allowHtml for customLanguageText

### ISSUE THREAD

**Issue by stefanschleich** [terminal42/contao-changelanguage#88]
I've just updated the extension to the latest version and now the option to allow HTML in the custom text field for languages is gone. This was very useful to show custom icons and have some control over the output of the items. Could you bring this back as an option?

**Comment by aschempp** [comment]
That probably happened because we switched from `OptionsWizard` to `MultiColumnWizard`. Can't see a reason not to allow HTML so I'll add it back in the next release.

**Comment by stefanschleich** [comment]
Great. Thanks :)

**Comment by stefanschleich** [comment]
I just saw that the allowHtml option in dca/tl_module.php is still there for the customLanguageText field (line 71). Do you have any idea why it doesn't work as expected?

**Comment by aschempp** [comment]
Because MultiColumnWizard allows to define that on every field.

**Comment by stefanschleich** [comment]
Alright. Got it.
