### ISSUE TITLE
Einstellung "Keep query parameters" wird ignoriert

### ISSUE THREAD

**Issue by uschek** [terminal42/contao-changelanguage#91]
In Version 2.x war die Einstellung der Query-Parameter im Sprachwechsler-Modul festgelegt. Seit Version 3.0 werden die Einstellungen an der jeweiligen Seite vorgenommen.

In Version 2.2.10 führte das Entfernen des Häkchens in den Moduleinstellungen zum gewünschten Effekt. Bei Version 3.0 hingegen werden die vorhandenen Query-Parameter bei leerem Input-Feld in den Seiteneinstellungen trotzdem übergeben. Gleiches gilt für die `rel="alternate"`-Tags.

**Comment by aschempp** [comment]
Du meinst es sollten alle Query-Parameter gelöscht werden wenn in der Seitenstruktur nichts eingegeben ist?

**Comment by uschek** [comment]
@aschempp Genau. Die Beschreibung des Input-Feldes [besagt](https://github.com/terminal42/contao-changelanguage/blob/edcd45c080c38d6bf13727c3cb200ab4abd677ff/languages/de/tl_page.xlf#L35): 

> Geben Sie eine kommaseparierte Liste von Query-Parametern ein, welche beim Sprachwechsel beibehalten werden sollen.

Daher gehe ich davon aus, dass bei leerem Input-Feld keine Query-Parameter übergeben werden, wenn die Sprache gewechselt wird.

**Comment by aschempp** [comment]
Ich kann dies nicht reproduzieren.

**Comment by Toflar** [comment]
Das kann ich auch nicht reproduzieren. Es werden korrekterweise keine Query-Parameter angehängt, wenn man nichts eingibt. Kann easy getestet werden, indem man einfach an eine beliebige Seite `?foo=bar` anhängt. Alle anderen Sprachen enthalten dann kein `?foo=bar` im Sprachwechsler. Wenn ich aber `foo` der entsprechenden Seiteneinstellung gebe, wird korrekterweise `?foo=bar` an jede Übersetzungs-URL angehängt. Funktioniert alles wie es soll.
