### ISSUE TITLE
Moved pages in non-master fallback tree lose connection

### ISSUE THREAD

**Issue by johannes-bittner** [terminal42/contao-changelanguage#92]
If you move a page in a related (=non-master fallback) page tree, the previously established link to the main language page in the master fallback page tree gets lost and the little signpost reappears in the page tree view. You therefore have to reset the main language page. This only happens in related page trees, not in the master fallback tree. (Contao 3.5.19 / changelanguage 3.1.0)

**Comment by connine** [comment]
I ran into the same problem and can confirm the issue (contao  3.5.9)

**Comment by aschempp** [comment]
Fixed in 1cf614b1ae0ce1462895bc5a8caad4f1eec89543
