### ISSUE TITLE
Fatal error: Class not found in

### ISSUE THREAD

**Issue by alnv** [terminal42/contao-changelanguage#93]
Ab changelanguage 3.1.0 gibt es ein "Fatal error" ( _Fatal error: Class 'MeinModelModel' not found in_  ) wenn man für eine Tabelle keine Model Klasse implementiert hat. 

Wäre es möglich In der 'ParentChildViewListener' Klasse die Methode 'getCurrentPage' zu erweitern:

In etwa so:

   ```
    protected function getCurrentPage()
    {
        /** @var Model $class */
        $class = $this->getModelClass();

        if (false === $this->current && class_exists( $class ) ) {
            $this->current = $class::findByPk($this->dataContainer->id);
        }

        if (null === $this->current) {
            return null;
        }

        $pageId = $this->current->pid ? $this->current->getRelated('pid')->jumpTo : $this->current->jumpTo;

        return PageModel::findWithDetails($pageId);
    }
```

Eventuell bittet das Contao-Framework eine alternative zu "class_exists( $class )" ?  …

**Comment by aschempp** [comment]
Sehe ich richtig dass ihr den `ParentChildViewListener` in euren eigenen Methoden verwendet?

Behoben in 7e65da2b9db2d5b4dbda50ea56733365afe0498c
