### ISSUE TITLE
Funktionen verbessern/optimieren

### ISSUE THREAD

**Issue by havutcuoglu** [terminal42/contao-changelanguage#94]
Lieber Changelanguage Entwickler,

ich finde es toll das der Erweiterung mittlerweile die Nachrichtenverknüpfung mit liefert.

Leider gibt es aber bei anderen Stellen Korrektur bedarf.
Einige davon ist euch bestimmt schon bekannt. Mir sind folgende Punkte aufgefallen, die nicht richtig oder nur zum Teil funktionieren.

1. Eigene Sprachtexte wird Ignoriert. Wenn 3 Seitenstartpunkte aktiviert ist aber nur 2 davon als eigene Texte definiert ist wird diese dann ignoriert.
2. Seitenstruktur wird in der Seitenauswahl nicht in der richtigen Reihenfolge ausgegeben. (Siehe Screenshot: seitenstruktur.png und auswahlstruktur.png)
3. Darstellung der FE-Modul ist fehlerhaft. (siehe screenshot: fe-modul.png)
4. "Query-Parameter beibehalten" wird ignoriert.
5. Bei der Wechsel von einem Nachricht zu dem anderen wird Fehlertext-ausgeben, wenn der Nachricht in der Sprache nicht existiert. Kann man hier nicht die Weiterleitung zu Übersicht integrieren?

Vielen Dank!

seitenstruktur.png
![seitenstruktur](https://cloud.githubusercontent.com/assets/11348417/21046456/1f7d88a2-be05-11e6-8b35-f20a94a652c4.png)

auswahlstruktur.png
![auswahlstruktur](https://cloud.githubusercontent.com/assets/11348417/21046457/1f7db02a-be05-11e6-9a74-6848319c224d.png)

fe-modul.png
![fe-modul](https://cloud.githubusercontent.com/assets/11348417/21046455/1f7d4266-be05-11e6-9858-8f16c37637a6.png)

**Comment by fritzmg** [comment]
ad 2.) https://github.com/contao/core/issues/8577
ad 4.) https://github.com/terminal42/contao-changelanguage/issues/91

**Comment by aschempp** [comment]
Nr. 1 kann ich nicht reproduzieren.
Nr. 2 behoben in 80a0497915053e7697a1f5e979572b8d04f24792, benötigt allerdings Contao 3.5.20
Nr. 3 behoben in ef9120feafe4104d54c7bd427853a438b7118289
Nr. 4 siehe #91 
Nr. 5 ich vermute es geht um's Frontend. Darauf hat changelanguage keinen Einfluss.

Für 1. falls nötig bitte ein neues Issue eröffnen. Generell sollte pro Problem/Frage/Feature ein Issue gemacht werden, damit diese separat behandelt werden können.

**Comment by fritzmg** [comment]
> Nr. 5 ich vermute es geht um's Frontend. Darauf hat changelanguage keinen Einfluss.

Das ist doch das Kern Feature von `changelanguage`? Reproduziert habe ich das Problem selbst jedoch noch nicht.

**Comment by aschempp** [comment]
Das **einzige** Feature von ChangeLanguage ist das Auswahlmenü. Ob die Module auf den entsprechenden Seiten damit umgehen können ist nicht Feature von ChangeLanguage.

**Comment by fritzmg** [comment]
Ja schon klar, aber was ist das gewünschte Verhalten wenn es für eine Nachricht kein Pendant in der anderen Sprache gibt? In `changelanguage` 2.0 wurde ja einfach nur auf die Reader Seite verlinkt, wenn ich mich richtig erinnere. Aber wie gesagt, habe das selbst noch nicht getestet.

**Comment by aschempp** [comment]
Ich denke die Diskussion gehört in's Forum und nicht in ein GitHub Issue

**Comment by havutcuoglu** [comment]
> Nr. 5 ich vermute es geht um's Frontend. Darauf hat changelanguage keinen Einfluss.

Genau es geht um's FE. Bei der alte Version war es wirklich so, wenn keine Nachricht in der anderen Sprache gabs, hat die Erweiterung auf Übersichtsseite weitergeleitet gehabt.

Mich stört es zwar weniger, aber wir bekommen immer wieder vom Kunden gesagt, warum das jetzt so ist.

> Für 1. falls nötig bitte ein neues Issue eröffnen. Generell sollte pro Problem/Frage/Feature ein Issue gemacht werden, damit diese separat behandelt werden können.

Ich werde die Nr. 1 nochmal testen, und bei bedarf erstelle ich ein separatem issue.

Vielen lieben Dank.
