### ISSUE TITLE
Field pid does not seem to be related

### ISSUE THREAD

**Issue by UB3RL33T** [terminal42/contao-changelanguage#98]
terminal42/contao-changelanguage 3.1.0

Ich nutze zusätzlich zu changelanguage das plugin psi-4ward/news4ward um die Blog- & Newslettereinträge auf meiner Seite zu managen. Nach einem Update von Contao 3.5.19 und damit auch ein Update von changelanguage auf 3.1.0 wird mir, sobald ich die Beiträge (Blog oder Newsletter) bearbeiten möchte folgender Fehler ausgeworfen:

Fatal error: Uncaught exception Exception with message Field pid does not seem to be related thrown in system/modules/core/library/Contao/Model.php on line 604

Ist das ein Kompatibilitätsproblem mit news4ward oder ein Bug?
Wie kann ich das Problem weiter eingrenzen?

<details>
#0 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/EventListener/BackendView/ParentChildViewListener.php(50): Contao\Model->getRelated('pid')

#1 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/EventListener/BackendView/AbstractViewListener.php(75): Terminal42\ChangeLanguage\EventListener\BackendView\ParentChildViewListener->getCurrentPage()

#2 composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/EventListener/BackendView/AbstractViewListener.php(52): Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener->onLoad(Object(Contao\DC_Table))

#3 system/modules/core/drivers/DC_Table.php(211): Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener->Terminal42\ChangeLanguage\EventListener\BackendView\{closure}(Object(Contao\DC_Table))

#4 system/modules/core/classes/Backend.php(408): Contao\DC_Table->__construct('tl_content', Array)

#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news4ward')

#6 contao/main.php(20): Contao\BackendMain->run()

#7 {main}

**Comment by amenk** [comment]
Bin ein Kollege von @UB3RL33T - was wir schon versucht hatten ist in news4ward die `pid` relation einzubauen. Das führte aber zu anderen Fehlern. Ich werde einen PR machen, in dem die Exception abgefangen wird, wenn es die Relation nicht gibt (leider habe ich keine Methode `Model::hasRelation()` gefunden.

**Comment by amenk** [comment]
@UB3RL33T https://github.com/terminal42/contao-changelanguage/pull/99#issuecomment-272792639

**Comment by aschempp** [comment]
Fixed in 7b956e216cf3ccd156b68c4324bb79df472da115
